"""``rsmm symbols`` — the engine symbol map (Minecraft-style mappings).

``data/symbols.json`` is the single source of truth: semantic name ->
engine function/global. Everything else is generated from it.

Subcommands:
  list                     Print the map, grouped by category.
  resolve <name>           Show one symbol's address + how it resolves.
  check                    Validate the map (CI-friendly; exits non-zero).
  gen                      Generate the loader C++ header + Python constants.
  ghidra-export [--json]   Emit a rename script for Ghidra (or a JSON
                           {addr: name} table for the MCP bridge) so the
                           functions stop showing up as FUN_xxxxxxxx.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from rsmm.engine.paths import REPO_ROOT
from rsmm.engine.symbols import SymbolMap, load_symbol_map, validate

# Generated artifacts — keep paths stable; CI --check compares against them.
LOADER_HEADER = REPO_ROOT / "src" / "loader" / "src" / "symbols.gen.h"
PYTHON_CONSTS = REPO_ROOT / "src" / "rsmm" / "engine" / "_symbols_gen.py"

_STATUS_GLYPH = {"ok": "OK ", "va": "VA ", "unverified": "?? "}


def _cmd_list(smap: SymbolMap) -> int:
    for cat in smap.categories:
        print(f"\n# {cat}")
        for s in sorted(smap.by_category(cat), key=lambda x: x.name):
            addr = s.preferred_addr(smap.preferred_base)
            glyph = _STATUS_GLYPH.get(s.status, "?? ")
            print(f"  [{glyph}] 0x{addr:09x}  {s.name}")
            if s.signature:
                print(f"              {s.signature}")
    print(f"\n{len(smap.symbols)} symbol(s).")
    return 0


def _cmd_resolve(smap: SymbolMap, name: str) -> int:
    s = smap.by_name(name)
    if s is None:
        print(f"no such symbol: {name}", file=sys.stderr)
        matches = [x.name for x in smap.symbols if name.lower() in x.name.lower()]
        if matches:
            print("did you mean: " + ", ".join(matches[:8]), file=sys.stderr)
        return 1
    addr = s.preferred_addr(smap.preferred_base)
    print(f"{s.name}")
    print(f"  address   0x{addr:x}  (preferred base 0x{smap.preferred_base:x})")
    print(f"  kind      {s.kind}")
    print(f"  category  {s.category}")
    print(f"  status    {s.status}")
    if s.pattern_name:
        print(f"  pattern   {s.pattern_name}  (version-resilient)")
    if s.signature:
        print(f"  signature {s.signature}")
    if s.note:
        print(f"  note      {s.note}")
    return 0


def _cmd_check(smap: SymbolMap) -> int:
    problems = validate(smap)
    if not problems:
        print(f"symbols OK: {len(smap.symbols)} symbol(s), no problems.")
        return 0
    print(f"{len(problems)} problem(s):", file=sys.stderr)
    for p in problems:
        print(f"  {p}", file=sys.stderr)
    return 1


def _cpp_ident(name: str) -> str:
    return name


def _gen_header(smap: SymbolMap) -> str:
    lines = [
        "// GENERATED by `rsmm symbols gen` from data/symbols.json — DO NOT EDIT.",
        "// Preferred-base addresses; the loader rebases by image-base delta and,",
        "// for `pattern`-backed symbols, re-resolves via data/function_patterns.json.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace Sym {",
        f"constexpr std::uintptr_t kPreferredBase = 0x{smap.preferred_base:x}ull;",
        "",
    ]
    for cat in smap.categories:
        lines.append(f"// --- {cat} ---")
        for s in sorted(smap.by_category(cat), key=lambda x: x.name):
            addr = s.preferred_addr(smap.preferred_base)
            pat = s.pattern_name or ""
            lines.append(f"constexpr std::uintptr_t {_cpp_ident(s.name)} = 0x{addr:x}ull;")
            if pat:
                lines.append(f'constexpr const char* {_cpp_ident(s.name)}_Pattern = "{pat}";')
        lines.append("")
    lines.append("}  // namespace Sym")
    lines.append("")
    return "\n".join(lines)


def _gen_python(smap: SymbolMap) -> str:
    lines = [
        '"""GENERATED by `rsmm symbols gen` from data/symbols.json — DO NOT EDIT."""',
        "from __future__ import annotations",
        "",
        f"PREFERRED_BASE = 0x{smap.preferred_base:x}",
        "",
        "# name -> preferred-base address",
        "ADDR: dict[str, int] = {",
    ]
    for s in sorted(smap.symbols, key=lambda x: x.name):
        addr = s.preferred_addr(smap.preferred_base)
        lines.append(f'    "{s.name}": 0x{addr:x},')
    lines.append("}")
    lines.append("")
    lines.append("# name -> function-pattern key (version-resilient), when available")
    lines.append("PATTERN: dict[str, str] = {")
    for s in sorted(smap.symbols, key=lambda x: x.name):
        if s.pattern_name:
            lines.append(f'    "{s.name}": "{s.pattern_name}",')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _cmd_gen(smap: SymbolMap, check: bool) -> int:
    header = _gen_header(smap)
    py = _gen_python(smap)
    targets = [(LOADER_HEADER, header), (PYTHON_CONSTS, py)]
    if check:
        stale = [p for p, content in targets if not p.is_file() or p.read_text() != content]
        if stale:
            print("generated symbol files are stale; run `rsmm symbols gen`:", file=sys.stderr)
            for p in stale:
                print(f"  {p.relative_to(REPO_ROOT)}", file=sys.stderr)
            return 1
        print("generated symbol files up to date.")
        return 0
    for p, content in targets:
        p.write_text(content, encoding="utf-8")
        print(f"wrote {p.relative_to(REPO_ROOT)}")
    return 0


def _cmd_ghidra_export(
    smap: SymbolMap, as_json: bool, out: Path | None, include_unverified: bool
) -> int:
    """Emit something that renames the live Ghidra DB so symbols are no
    longer FUN_xxxxxxxx. ``--json`` prints an {addr_hex: name} table (for the
    Ghidra MCP bridge); otherwise a runnable Ghidra Python (Jython) script.

    ``unverified`` symbols carry addresses from an older corpus that may
    point at the wrong function in the current DB, so they are skipped
    unless ``--include-unverified`` is passed."""
    chosen = [
        s
        for s in smap.symbols
        if include_unverified or s.status != "unverified"
    ]
    rows = [
        (s.preferred_addr(smap.preferred_base), s.name, s.kind)
        for s in sorted(chosen, key=lambda x: x.preferred_addr(smap.preferred_base))
    ]
    if as_json:
        table = {f"0x{addr:x}": name for addr, name, _ in rows}
        text = json.dumps(table, indent=2)
        if out:
            out.write_text(text, encoding="utf-8")
            print(f"wrote {out}")
        else:
            print(text)
        return 0
    script = [
        "# GENERATED by `rsmm symbols ghidra-export` — run inside Ghidra (Script Manager).",
        "# Renames functions/data at the preferred base so they stop reading as FUN_xxxxxxxx.",
        "from ghidra.program.model.symbol import SourceType",
        "fm = currentProgram.getFunctionManager()",
        "base = currentProgram.getImageBase()",
        f"pref = base.getNewAddress(0x{smap.preferred_base:x})",
        "delta = base.getOffset() - pref.getOffset()",
        "renamed = 0",
        "for addr_int, name, kind in [",
    ]
    for addr, name, kind in rows:
        script.append(f'    (0x{addr:x}, "{name}", "{kind}"),')
    script += [
        "]:",
        "    a = base.getNewAddress(addr_int + delta)",
        '    if kind == "function":',
        "        fn = fm.getFunctionAt(a)",
        "        if fn is not None:",
        "            fn.setName(name, SourceType.USER_DEFINED); renamed += 1",
        "    else:",
        "        createLabel(a, name, True); renamed += 1",
        'print("renamed %d symbol(s)" % renamed)',
        "",
    ]
    text = "\n".join(script)
    if out:
        out.write_text(text, encoding="utf-8")
        print(f"wrote {out}")
    else:
        print(text)
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="rsmm symbols", description="Engine symbol map")
    sub = ap.add_subparsers(dest="cmd")
    sub.add_parser("list", help="print the map grouped by category")
    pr = sub.add_parser("resolve", help="show one symbol")
    pr.add_argument("name")
    sub.add_parser("check", help="validate the map (exits non-zero on problems)")
    pg = sub.add_parser("gen", help="generate loader header + python constants")
    pg.add_argument("--check", action="store_true", help="fail if generated files are stale")
    pe = sub.add_parser("ghidra-export", help="emit a Ghidra rename script (or --json table)")
    pe.add_argument("--json", action="store_true", help="emit {addr: name} JSON instead")
    pe.add_argument("-o", "--out", type=Path, default=None, help="write to file instead of stdout")
    pe.add_argument(
        "--include-unverified",
        action="store_true",
        help="also rename symbols whose address is from an older corpus (risky)",
    )
    args = ap.parse_args(argv)

    smap = load_symbol_map()
    if args.cmd in (None, "list"):
        return _cmd_list(smap)
    if args.cmd == "resolve":
        return _cmd_resolve(smap, args.name)
    if args.cmd == "check":
        return _cmd_check(smap)
    if args.cmd == "gen":
        return _cmd_gen(smap, args.check)
    if args.cmd == "ghidra-export":
        return _cmd_ghidra_export(smap, args.json, args.out, args.include_unverified)
    ap.print_help()
    return 1


if __name__ == "__main__":
    sys.exit(main())
