#!/usr/bin/env python3
"""
Texture-replacement mod generator (donor-swap, cooked-only).

The cooked `.Texture.dxt` / `.tpi` container is a custom oCTextSaver
binary, *not* a plain DDS. Building one from a PNG source requires a
full oCTexture re-encoder that does not exist yet. Until it does, the
practical workflow is donor-swap: pick a cooked texture you like
(donor) and drop its bytes onto the target's cooked path.

This tool packages that pattern:

    # Browse available textures by decoded substring.
    rsmm texture --list --grep Hero_Romeo

    # Build a mod that replaces Romeo's portrait with SunWukong's.
    rsmm texture --mod-id RomeoIsMonkey \\
        'Ui/BookMenu/Heroes/UI_HeroPortrait_Romeo_Active.png.Texture.dxt=Ui/BookMenu/Heroes/UI_HeroPortrait_SunWukong_Active.png.Texture.dxt'

Each assignment is `<target_decoded_path>=<donor_decoded_path>` and
both must appear in asset_map.json. The donor's cooked bytes are
copied into `mods/<id>/assets/<target_decoded_path>`. Install with
`./rsmm apply` as usual.

PNG support (Phase B in NEXT_STEPS.md) is deferred until the oCTexture
container is reverse-engineered. The accepted shape: PNG -> DDS payload
via texconv/Pillow, then wrap in the oCTextSaver container with the
correct width/height/stride header.
"""

from __future__ import annotations
import argparse
import json
import shutil
import sys
from pathlib import Path

from rsmm.engine.paths import (
    REPO_ROOT,
    DATA_DIR,
    MODS_DIR,
    ASSET_MAP_JSON,
    ASSET_MAP_CSV,
    DEFAULT_GAME_DIR as DEFAULT_GAME,
    COOKING_SUBDIR,
)

TEXTURE_SUFFIXES = (
    ".png.Texture.dxt",
    ".tga.Texture.dxt",
    ".tga.Texture.nrm",
)


def load_asset_map() -> dict[str, str]:
    return json.loads((ASSET_MAP_JSON).read_text(encoding="utf-8"))


def index_textures(asset_map: dict[str, str], cooking: Path) -> dict[str, Path]:
    """decoded path (forward-slash) -> cooked file Path."""
    out: dict[str, Path] = {}
    for enc_rel, dec_rel in asset_map.items():
        if not any(dec_rel.endswith(suf) for suf in TEXTURE_SUFFIXES):
            continue
        p = cooking / Path(*enc_rel.split("\\"))
        if not p.exists():
            continue
        out[dec_rel.replace("\\", "/")] = p
    return out


def cmd_list(textures: dict[str, Path], grep: str | None) -> int:
    needle = grep.lower() if grep else None
    rows = sorted(textures)
    shown = 0
    for dec in rows:
        if needle and needle not in dec.lower():
            continue
        sz = textures[dec].stat().st_size
        print(f"  {sz:>10d}  {dec}")
        shown += 1
    print(f"\n# {shown} of {len(rows)} textures")
    return 0


def parse_pairs(args: list[str]) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for raw in args:
        if "=" not in raw:
            raise SystemExit(f"assignment must be TARGET=DONOR, got: {raw!r}")
        tgt, _, donor = raw.partition("=")
        pairs.append((tgt.strip().replace("\\", "/"),
                      donor.strip().replace("\\", "/")))
    return pairs


def cmd_make(args, textures: dict[str, Path]) -> int:
    pairs = parse_pairs(args.assignments)
    mod_dir = MODS_DIR / args.mod_id
    assets = mod_dir / "assets"
    if mod_dir.exists() and not args.force:
        print(f"mod dir exists: {mod_dir}. Use --force to overwrite.",
              file=sys.stderr)
        return 1
    mod_dir.mkdir(parents=True, exist_ok=True)
    assets.mkdir(parents=True, exist_ok=True)

    applied: list[tuple[str, str]] = []
    for tgt, donor in pairs:
        if tgt not in textures:
            print(f"  [skip] target not in asset_map: {tgt!r}", file=sys.stderr)
            continue
        if donor not in textures:
            print(f"  [skip] donor not in asset_map: {donor!r}", file=sys.stderr)
            continue
        dst = assets / tgt
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(textures[donor], dst)
        applied.append((tgt, donor))

    if not applied:
        print("Nothing applied.", file=sys.stderr)
        return 1

    desc = args.name or f"Donor-swap of {len(applied)} texture(s)"
    (mod_dir / "manifest.toml").write_text(
        "# Generated by rsmm texture\n"
        "[mod]\n"
        f'id          = "{args.mod_id}"\n'
        f'name        = "{desc}"\n'
        f'version     = "1.0.0"\n'
        f'author      = "{args.author}"\n'
        f'description = "Replaces cooked textures by byte-copying donor files."\n'
        "enabled     = true\n",
        encoding="utf-8",
    )
    lines = [f"# {args.mod_id}", "", "Texture swaps:", ""]
    for tgt, donor in applied:
        lines.append(f"- `{tgt}` <- `{donor}`")
    lines += ["", "Install: `./rsmm apply`", ""]
    (mod_dir / "README.md").write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote mod {args.mod_id} with {len(applied)} swap(s).")
    for tgt, donor in applied:
        print(f"  {tgt}\n    <- {donor}")
    print("\nNext: ./rsmm apply")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--game-dir", type=Path, default=DEFAULT_GAME)
    ap.add_argument("--list", action="store_true",
                    help="print every cooked texture path and exit")
    ap.add_argument("--grep", default=None,
                    help="substring filter for --list")
    ap.add_argument("--mod-id", default="TextureMod",
                    help="output mod folder name under mods/")
    ap.add_argument("--name", default=None)
    ap.add_argument("--author", default="RSMM")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("assignments", nargs="*",
                    help="TARGET_PATH=DONOR_PATH pairs")
    args = ap.parse_args()

    cooking = args.game_dir / COOKING_SUBDIR
    if not cooking.is_dir():
        print(f"_Cooking not found: {cooking}", file=sys.stderr)
        return 1
    textures = index_textures(load_asset_map(), cooking)
    if not textures:
        print("No textures found in asset_map.", file=sys.stderr)
        return 1

    if args.list:
        return cmd_list(textures, args.grep)
    if not args.assignments:
        ap.print_help()
        return 2
    return cmd_make(args, textures)


if __name__ == "__main__":
    sys.exit(main())
