#!/usr/bin/env python3
"""
Generate a mod that overrides a URL in ApplicationSettings.ot.

The four buttons at the bottom of Ravenswatch's main menu (Discord,
Roadmap, Bug Reports, "Latest update") each open an external URL defined
in `DarkTalesResources/ApplicationSettings.ot`:

  m_sDiscordUrl     -> Discord invite
  m_sPatchNoteUrl   -> patch notes / roadmap
  m_sBugReportsUrl  -> Nacon support page
  m_sNewUpdateUrl   -> Steam DLC page

This tool reads the live file, replaces the requested URL(s), and emits
a mod that uses the `_root/` prefix supported by `apply_mods.py` to ship
a replacement of the top-level `ApplicationSettings.ot`.

Combined with `rsmm text` (which renames the button label),
this hijacks a main-menu button into doing whatever you want — opening a
local HTML mod-list, an external mod hub, your repo, etc.

Usage:

  rsmm url --list
  rsmm url --mod-id ModsHub \\
      DiscordUrl=https://github.com/you/your-mod-hub
"""

from __future__ import annotations
import argparse
import re
import sys
from pathlib import Path

from rsmm.engine.paths import (
    REPO_ROOT,
    DATA_DIR,
    MODS_DIR,
    ASSET_MAP_JSON,
    ASSET_MAP_CSV,
    DEFAULT_GAME_DIR as DEFAULT_GAME,
    COOKING_SUBDIR,
)

KNOWN_KEYS = ["DiscordUrl", "PatchNoteUrl", "BugReportsUrl", "NewUpdateUrl",
              "SignToolDescUrl"]


def find_urls(text: str) -> dict[str, tuple[int, int, str]]:
    """name -> (line, byte_offset_of_value, value).

    Matches lines of the form `s|m_s<Name>=<value>`.
    """
    out: dict[str, tuple[int, int, str]] = {}
    pos = 0
    for line_no, line in enumerate(text.splitlines(keepends=True), start=1):
        m = re.match(r"s\|m_s(\w+)=(.*?)(\r?\n?)$", line)
        if m and m.group(1) in KNOWN_KEYS:
            value_offset = pos + len(f"s|m_s{m.group(1)}=")
            out[m.group(1)] = (line_no, value_offset, m.group(2))
        pos += len(line)
    return out


def parse_assignments(args: list[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for raw in args:
        if "=" not in raw:
            raise SystemExit(f"bad assignment {raw!r} (expected NAME=URL)")
        k, _, v = raw.partition("=")
        out[k.strip()] = v.strip()
    return out


def cmd_list(text: str) -> int:
    urls = find_urls(text)
    if not urls:
        print("no known URL keys found")
        return 0
    for name, (line, _, val) in urls.items():
        print(f"  {name:<18s} (line {line}): {val}")
    return 0


def cmd_make(args, settings: Path, text: str) -> int:
    overrides = parse_assignments(args.assignments)
    if not overrides:
        print("nothing to override", file=sys.stderr)
        return 2
    urls = find_urls(text)
    new_text = text
    applied: list[tuple[str, str, str]] = []
    for name, new_url in overrides.items():
        if name not in urls:
            print(f"  [skip] unknown URL key {name!r} "
                  f"(known: {', '.join(KNOWN_KEYS)})", file=sys.stderr)
            continue
        old_url = urls[name][2]
        if old_url == new_url:
            continue
        # do a precise replacement on the exact line content
        old_line = f"s|m_s{name}={old_url}\n"
        new_line = f"s|m_s{name}={new_url}\n"
        if old_line not in new_text:
            # CRLF case
            old_line_crlf = old_line[:-1] + "\r\n"
            new_line_crlf = new_line[:-1] + "\r\n"
            if old_line_crlf in new_text:
                new_text = new_text.replace(old_line_crlf, new_line_crlf, 1)
            else:
                print(f"  [warn] couldn't locate exact line for {name}; skipping",
                      file=sys.stderr)
                continue
        else:
            new_text = new_text.replace(old_line, new_line, 1)
        applied.append((name, old_url, new_url))

    if not applied:
        print("nothing to write", file=sys.stderr)
        return 1

    mod_dir = MODS_DIR / args.mod_id
    if mod_dir.exists() and not args.force:
        print(f"mod dir exists: {mod_dir}; use --force", file=sys.stderr)
        return 1
    dest = mod_dir / "assets" / "_root" / "DarkTalesResources" / "ApplicationSettings.ot"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(new_text, encoding="utf-8")

    manifest = mod_dir / "manifest.toml"
    manifest.write_text(
        f"# Generated by rsmm url\n"
        f"[mod]\n"
        f'id          = "{args.mod_id}"\n'
        f'name        = "{args.name or args.mod_id}"\n'
        f'version     = "1.0.0"\n'
        f'author      = "{args.author}"\n'
        f'description = "Redirects main-menu external URLs."\n'
        f"enabled     = true\n",
        encoding="utf-8",
    )
    readme = mod_dir / "README.md"
    lines = [f"# {args.mod_id}", "", "Redirected URLs:", ""]
    for name, old, new in applied:
        lines.append(f"- `{name}`")
        lines.append(f"    was: {old}")
        lines.append(f"    now: {new}")
    lines += ["", "Install: `./rsmm apply`.", ""]
    readme.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote mod {args.mod_id} with {len(applied)} URL override(s):")
    for name, old, new in applied:
        print(f"  {name}: {old} -> {new}")
    print("\nNext: ./rsmm apply")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--game-dir", type=Path, default=DEFAULT_GAME)
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--mod-id", default="UrlMod")
    ap.add_argument("--name", default=None)
    ap.add_argument("--author", default="RSMM")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("assignments", nargs="*",
                    help="NAME=URL pairs (e.g. DiscordUrl=https://...)")
    args = ap.parse_args()

    settings = args.game_dir / "DarkTalesResources" / "ApplicationSettings.ot"
    if not settings.exists():
        print(f"ApplicationSettings.ot not found at {settings}", file=sys.stderr)
        return 1
    text = settings.read_text(encoding="utf-8")

    if args.list:
        return cmd_list(text)
    return cmd_make(args, settings, text)


if __name__ == "__main__":
    sys.exit(main())
