-- GENERATED by `rsmm symbols gen` from data/symbols.json — DO NOT EDIT.
-- Semantic name -> { pattern = <FUN_ for fn_resolve>, offset = <int> }.
-- Feed pattern to rsmm._internal.resolve(), add offset, then call.
return {
  ["Entity_FindComponentByType"] = { pattern = "FUN_1406ca380", offset = 0x0 },
  ["Entry_Ctor"] = { pattern = "FUN_140214bb0", offset = 0x0 },
  ["Event_LevelUp"] = { pattern = "FUN_1401f6410", offset = 0x0 },
  ["Event_RunEnd"] = { pattern = "FUN_1401f51e0", offset = 0x0 },
  ["MagicalObject_SpawnAllObjects"] = { pattern = "FUN_1402586f0", offset = 0x70 },
  ["Resource_LookupByPath"] = { pattern = "FUN_140487040", offset = 0x0 },
  ["SkinGrid_Populate"] = { pattern = "FUN_1401f0f10", offset = 0x0 },
  ["String_Assign"] = { pattern = "FUN_1405288b0", offset = 0x0 },
  ["Vector_Grow"] = { pattern = "FUN_140154c20", offset = 0x0 },
}
