-- GENERATED by `rsmm symbols gen` from data/symbols.json — DO NOT EDIT.
-- Semantic name -> { pattern = <FUN_ for fn_resolve>, offset = <int>,
--                    sig = <native call signature: ret code + arg codes> }.
-- rsmm.lua's R.engine.call(name, ...) resolves the pattern, adds the
-- offset, and passes `sig` to rsmm._internal.call so mods call by name
-- with no manual signature. Codes: v=void i=int32 u=uint32 p/l=ptr/int64
-- f=float d=double s=string (see script_lua.cpp::lua_call_native).
return {
  ["Analytics_SubmitNamedEvent"] = { pattern = "FUN_1401fa470", offset = 0x0, sig = "vpppu" },
  ["Entity_AllocInstance"] = { pattern = "FUN_14068fe90", offset = 0x0, sig = "pp" },
  ["Entity_FindComponentByType"] = { pattern = "FUN_1406ca380", offset = 0x0, sig = "ppp" },
  ["Entity_FindMagicalObjectComponent"] = { pattern = "FUN_1406e2250", offset = 0x0, sig = "ppp" },
  ["Entity_ModifyHealth"] = { pattern = "FUN_140399a10", offset = 0x0, sig = "vpfp" },
  ["Entry_Ctor"] = { pattern = "FUN_140214bb0", offset = 0x0, sig = "vpu" },
  ["Event_LevelUp"] = { pattern = "FUN_1401f6410", offset = 0x0, sig = "ppp" },
  ["Event_RunEnd"] = { pattern = "FUN_1401f51e0", offset = 0x0, sig = "ppp" },
  ["MagicalObjectPool_Grow"] = { pattern = "FUN_1401550d0", offset = 0x0, sig = "vpuu" },
  ["MagicalObjectPool_SourceLookup"] = { pattern = "FUN_1402590c0", offset = 0x0, sig = "pppp" },
  ["MagicalObject_SpawnAllObjects"] = { pattern = "FUN_1402586f0", offset = 0x70, sig = "vpp" },
  ["NamedEvent_ChannelMap_Find"] = { pattern = "FUN_14066cc50", offset = 0x0, sig = "pppp" },
  ["NamedEvent_Delete"] = { pattern = "FUN_140126da0", offset = 0x0, sig = "vp" },
  ["NamedEvent_Dispatch"] = { pattern = "FUN_14066a700", offset = 0x0, sig = "vpp" },
  ["NamedEvent_GiveMagicalObject_Ctor"] = { pattern = "FUN_14030f430", offset = 0x0, sig = "pp" },
  ["NamedEvent_HeroSubscribeAll"] = { pattern = "FUN_140391d30", offset = 0x0, sig = "vp" },
  ["NamedEvent_Id_FromCrc"] = { pattern = "FUN_14051e0e0", offset = 0x0, sig = "uuu" },
  ["NamedEvent_NetSend"] = { pattern = "FUN_1407205a0", offset = 0x0, sig = "vpp" },
  ["NamedEvent_NetSendToPeer"] = { pattern = "FUN_140720630", offset = 0x0, sig = "vppp" },
  ["Netcode_Channel_LookupById"] = { pattern = "FUN_140241150", offset = 0x0, sig = "pppp" },
  ["Netcode_Channel_Unsubscribe"] = { pattern = "FUN_1401c8660", offset = 0x0, sig = "vpp" },
  ["Netcode_EntityReplSetup"] = { pattern = "FUN_140720c10", offset = 0x0, sig = "vp" },
  ["Registry_EnumInstances"] = { pattern = "FUN_140240e50", offset = 0x0, sig = "pppp" },
  ["Resource_LookupByPath"] = { pattern = "FUN_140487040", offset = 0x0, sig = "psppp" },
  ["SkinGrid_Populate"] = { pattern = "FUN_1401f0f10", offset = 0x0, sig = "vpp" },
  ["String_Assign"] = { pattern = "FUN_1405288b0", offset = 0x0, sig = "vpp" },
  ["Vector_Grow"] = { pattern = "FUN_140154c20", offset = 0x0, sig = "vplu" },
}
