-- GENERATED by `rsmm symbols gen` from data/symbols.json — DO NOT EDIT.
-- Semantic name -> { pattern = <FUN_ for fn_resolve>, offset = <int>,
--                    sig = <native call signature: ret code + arg codes> }.
-- rsmm.lua's R.engine.call(name, ...) resolves the pattern, adds the
-- offset, and passes `sig` to rsmm._internal.call so mods call by name
-- with no manual signature. Codes: v=void i=int32 u=uint32 p/l=ptr/int64
-- f=float d=double s=string (see script_lua.cpp::lua_call_native).
return {
  ["Analytics_SubmitNamedEvent"] = { pattern = "FUN_1401fa470", offset = 0x0, sig = "vpppu" },
  ["Entity_AllocInstance"] = { pattern = "FUN_14068fe90", offset = 0x0, sig = "pp" },
  ["Entity_FindComponentByType"] = { pattern = "FUN_1406ca380", offset = 0x0, sig = "ppp" },
  ["Entity_FindMagicalObjectComponent"] = { pattern = "FUN_1406e2250", offset = 0x0, sig = "ppp" },
  ["Entry_Ctor"] = { pattern = "FUN_140214bb0", offset = 0x0, sig = "vpu" },
  ["Event_LevelUp"] = { pattern = "FUN_1401f6410", offset = 0x0, sig = "ppp" },
  ["Event_RunEnd"] = { pattern = "FUN_1401f51e0", offset = 0x0, sig = "ppp" },
  ["MagicalObjectPool_Grow"] = { pattern = "FUN_1401550d0", offset = 0x0, sig = "vpuu" },
  ["MagicalObjectPool_SourceLookup"] = { pattern = "FUN_1402590c0", offset = 0x0, sig = "pppp" },
  ["MagicalObject_SpawnAllObjects"] = { pattern = "FUN_1402586f0", offset = 0x70, sig = "vpp" },
  ["Resource_LookupByPath"] = { pattern = "FUN_140487040", offset = 0x0, sig = "psppp" },
  ["SkinGrid_Populate"] = { pattern = "FUN_1401f0f10", offset = 0x0, sig = "vpp" },
  ["String_Assign"] = { pattern = "FUN_1405288b0", offset = 0x0, sig = "vpp" },
  ["Vector_Grow"] = { pattern = "FUN_140154c20", offset = 0x0, sig = "vplu" },
}
