[strings]
mod_name                = "The Forgotten"
mod_desc                = "Paquete de contenido que añade héroe, enemigos, jefe y objetos"
Vindicator_name         = "El Vindicador"
Vindicator_desc         = "Un guerrero sagrado que canaliza poder divino."
Vindicator_HolyStrike   = "Golpe Sagrado"
Vindicator_DivineShield = "Escudo Divino"
Vindicator_SacredLight  = "Luz Sagrada"
Vindicator_Judgment     = "Juicio"
CursedKnight_name       = "Caballero Maldito"
CursedKnight_desc       = "Un caballero caído atado a la magia oscura."
ForgottenKing_name      = "El Rey Olvidado"
ForgottenKing_desc      = "Un gobernante antaño noble, consumido por la corrupción."
ForgottenKing_intro     = "¿Te atreves a desafiar al Rey Olvidado?"
ForgottenKing_phase2    = "Sientes el peso de antiguas maldiciones..."
ForgottenKing_phase3    = "¡LA CORRUPCIÓN LO CONSUME TODO!"
VindicatorsOath_name    = "Juramento del Vindicador"
VindicatorsOath_desc    = "Otorga armadura adicional y curación al derrotar enemigos malditos."
CursedCrown_name        = "Corona Maldita"
CursedCrown_desc        = "Aumenta el daño en un 50% pero reduce la salud máxima en un 20%."
SacredRelic_name        = "Reliquia Sagrada"
SacredRelic_desc        = "Los aliados cercanos regeneran salud gradualmente."
