/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SettingsRouteImport } from './routes/settings';
import { Route as ProfilesRouteImport } from './routes/profiles';
import { Route as ConflictsRouteImport } from './routes/conflicts';
import { Route as BrowseRouteImport } from './routes/browse';
import { Route as AboutRouteImport } from './routes/about';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ModSlugRouteImport } from './routes/mod.$slug';

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any);
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any);
const ConflictsRoute = ConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => rootRouteImport,
} as any);
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const ModSlugRoute = ModSlugRouteImport.update({
  id: '/mod/$slug',
  path: '/mod/$slug',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/browse': typeof BrowseRoute;
  '/conflicts': typeof ConflictsRoute;
  '/profiles': typeof ProfilesRoute;
  '/settings': typeof SettingsRoute;
  '/mod/$slug': typeof ModSlugRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/browse': typeof BrowseRoute;
  '/conflicts': typeof ConflictsRoute;
  '/profiles': typeof ProfilesRoute;
  '/settings': typeof SettingsRoute;
  '/mod/$slug': typeof ModSlugRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/browse': typeof BrowseRoute;
  '/conflicts': typeof ConflictsRoute;
  '/profiles': typeof ProfilesRoute;
  '/settings': typeof SettingsRoute;
  '/mod/$slug': typeof ModSlugRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/about'
    | '/browse'
    | '/conflicts'
    | '/profiles'
    | '/settings'
    | '/mod/$slug';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/about'
    | '/browse'
    | '/conflicts'
    | '/profiles'
    | '/settings'
    | '/mod/$slug';
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/browse'
    | '/conflicts'
    | '/profiles'
    | '/settings'
    | '/mod/$slug';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  BrowseRoute: typeof BrowseRoute;
  ConflictsRoute: typeof ConflictsRoute;
  ProfilesRoute: typeof ProfilesRoute;
  SettingsRoute: typeof SettingsRoute;
  ModSlugRoute: typeof ModSlugRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/profiles': {
      id: '/profiles';
      path: '/profiles';
      fullPath: '/profiles';
      preLoaderRoute: typeof ProfilesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/conflicts': {
      id: '/conflicts';
      path: '/conflicts';
      fullPath: '/conflicts';
      preLoaderRoute: typeof ConflictsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/browse': {
      id: '/browse';
      path: '/browse';
      fullPath: '/browse';
      preLoaderRoute: typeof BrowseRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/mod/$slug': {
      id: '/mod/$slug';
      path: '/mod/$slug';
      fullPath: '/mod/$slug';
      preLoaderRoute: typeof ModSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrowseRoute: BrowseRoute,
  ConflictsRoute: ConflictsRoute,
  ProfilesRoute: ProfilesRoute,
  SettingsRoute: SettingsRoute,
  ModSlugRoute: ModSlugRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
