// GENERATED by `rsmm symbols gen` from data/symbols.json — DO NOT EDIT.
// Typed, pattern-resolved engine call accessors (the Minecraft-style
// 'mappings become callable methods' layer). Each accessor resolves its
// byte pattern via fn_resolve, so it survives game updates.
#pragma once
#include "fn_resolver.h"
#include "symbols.gen.h"
#include <cstdint>

namespace engine {

// AchievementDef_PostLoad  (AchievementDef_PostLoad)
//   bool(void* definition)
using AchievementDef_PostLoad_fn = uint32_t(*)(void*);
inline AchievementDef_PostLoad_fn AchievementDef_PostLoad() {
    return reinterpret_cast<AchievementDef_PostLoad_fn>(rsmm::fn_resolve(Sym::AchievementDef_PostLoad_Pattern));
}

// Analytics_SubmitNamedEvent  (Analytics_SubmitNamedEvent)
//   void(void* analytics_mgr, void* payload_kv, StringDesc* event_name, char has_run_ctx)
using Analytics_SubmitNamedEvent_fn = void(*)(void*, void*, void*, uint32_t);
inline Analytics_SubmitNamedEvent_fn Analytics_SubmitNamedEvent() {
    return reinterpret_cast<Analytics_SubmitNamedEvent_fn>(rsmm::fn_resolve(Sym::Analytics_SubmitNamedEvent_Pattern));
}

// BookController_ResolveSettings  (BookController_ResolveSettings)
//   void(oCDtEntityCpnt3DBookController* self)
using BookController_ResolveSettings_fn = void(*)(void*);
inline BookController_ResolveSettings_fn BookController_ResolveSettings() {
    return reinterpret_cast<BookController_ResolveSettings_fn>(rsmm::fn_resolve(Sym::BookController_ResolveSettings_Pattern));
}

// BookController_ResolveTabs  (BookController_ResolveTabs)
//   void(oCDtEntityCpnt3DBookController* self)
using BookController_ResolveTabs_fn = void(*)(void*);
inline BookController_ResolveTabs_fn BookController_ResolveTabs() {
    return reinterpret_cast<BookController_ResolveTabs_fn>(rsmm::fn_resolve(Sym::BookController_ResolveTabs_Pattern));
}

// ChallengeDef_PostLoad  (ChallengeDef_PostLoad)
//   bool(void* definition)
using ChallengeDef_PostLoad_fn = uint32_t(*)(void*);
inline ChallengeDef_PostLoad_fn ChallengeDef_PostLoad() {
    return reinterpret_cast<ChallengeDef_PostLoad_fn>(rsmm::fn_resolve(Sym::ChallengeDef_PostLoad_Pattern));
}

// ChallengeUnlock_IsUnlocked  (ChallengeUnlock_IsUnlocked)
//   bool(void* condition_data)
using ChallengeUnlock_IsUnlocked_fn = uint32_t(*)(void*);
inline ChallengeUnlock_IsUnlocked_fn ChallengeUnlock_IsUnlocked() {
    return reinterpret_cast<ChallengeUnlock_IsUnlocked_fn>(rsmm::fn_resolve(Sym::ChallengeUnlock_IsUnlocked_Pattern));
}

// Definition_PostLoad  (Definition_PostLoad)
//   bool(void* definition)
using Definition_PostLoad_fn = uint32_t(*)(void*);
inline Definition_PostLoad_fn Definition_PostLoad() {
    return reinterpret_cast<Definition_PostLoad_fn>(rsmm::fn_resolve(Sym::Definition_PostLoad_Pattern));
}

// Definition_PreUnload  (Definition_PreUnload)
//   void(void*)
using Definition_PreUnload_fn = void(*)(void*);
inline Definition_PreUnload_fn Definition_PreUnload() {
    return reinterpret_cast<Definition_PreUnload_fn>(rsmm::fn_resolve(Sym::Definition_PreUnload_Pattern));
}

// DreamShardDef_PostLoad  (DreamShardDef_PostLoad)
//   bool(void* definition)
using DreamShardDef_PostLoad_fn = uint32_t(*)(void*);
inline DreamShardDef_PostLoad_fn DreamShardDef_PostLoad() {
    return reinterpret_cast<DreamShardDef_PostLoad_fn>(rsmm::fn_resolve(Sym::DreamShardDef_PostLoad_Pattern));
}

// EnemyCampTierDef_PostLoad  (EnemyCampTierDef_PostLoad)
//   bool(void* definition)
using EnemyCampTierDef_PostLoad_fn = uint32_t(*)(void*);
inline EnemyCampTierDef_PostLoad_fn EnemyCampTierDef_PostLoad() {
    return reinterpret_cast<EnemyCampTierDef_PostLoad_fn>(rsmm::fn_resolve(Sym::EnemyCampTierDef_PostLoad_Pattern));
}

// EntityValueEntry_Ctor  (EntityValueEntry_Ctor)
//   void(void*, void*)
using EntityValueEntry_Ctor_fn = void(*)(void*, void*);
inline EntityValueEntry_Ctor_fn EntityValueEntry_Ctor() {
    return reinterpret_cast<EntityValueEntry_Ctor_fn>(rsmm::fn_resolve(Sym::EntityValueEntry_Ctor_Pattern));
}

// EntityValueOverride_Alloc  (EntityValueOverride_Alloc)
//   void*(void*, uint32_t, uint32_t)
using EntityValueOverride_Alloc_fn = void*(*)(void*, uint32_t, uint32_t);
inline EntityValueOverride_Alloc_fn EntityValueOverride_Alloc() {
    return reinterpret_cast<EntityValueOverride_Alloc_fn>(rsmm::fn_resolve(Sym::EntityValueOverride_Alloc_Pattern));
}

// EntityValueStore_ApplyModifierEvent  (EntityValueStore_ApplyModifierEvent)
//   void(void* store, void* modifierEvent, void* a3, void* a4)
using EntityValueStore_ApplyModifierEvent_fn = void(*)(void*, void*, void*, void*);
inline EntityValueStore_ApplyModifierEvent_fn EntityValueStore_ApplyModifierEvent() {
    return reinterpret_cast<EntityValueStore_ApplyModifierEvent_fn>(rsmm::fn_resolve(Sym::EntityValueStore_ApplyModifierEvent_Pattern));
}

// EntityValueStore_InitBaseValues  (EntityValueStore_InitBaseValues)
//   void(void* store)
using EntityValueStore_InitBaseValues_fn = void(*)(void*);
inline EntityValueStore_InitBaseValues_fn EntityValueStore_InitBaseValues() {
    return reinterpret_cast<EntityValueStore_InitBaseValues_fn>(rsmm::fn_resolve(Sym::EntityValueStore_InitBaseValues_Pattern));
}

// EntityValueStore_Recompute  (EntityValueStore_Recompute)
//   void(void* store, void* valueDef)
using EntityValueStore_Recompute_fn = void(*)(void*, void*);
inline EntityValueStore_Recompute_fn EntityValueStore_Recompute() {
    return reinterpret_cast<EntityValueStore_Recompute_fn>(rsmm::fn_resolve(Sym::EntityValueStore_Recompute_Pattern));
}

// EntityValueUnion_Compare  (EntityValueUnion_Compare)
//   uint32_t(void*, void*)
using EntityValueUnion_Compare_fn = uint32_t(*)(void*, void*);
inline EntityValueUnion_Compare_fn EntityValueUnion_Compare() {
    return reinterpret_cast<EntityValueUnion_Compare_fn>(rsmm::fn_resolve(Sym::EntityValueUnion_Compare_Pattern));
}

// EntityValueUnion_CopyAssign  (EntityValueUnion_CopyAssign)
//   void(void*, void*)
using EntityValueUnion_CopyAssign_fn = void(*)(void*, void*);
inline EntityValueUnion_CopyAssign_fn EntityValueUnion_CopyAssign() {
    return reinterpret_cast<EntityValueUnion_CopyAssign_fn>(rsmm::fn_resolve(Sym::EntityValueUnion_CopyAssign_Pattern));
}

// EntityValueUnion_DefaultCtor  (EntityValueUnion_DefaultCtor)
//   void*(void*)
using EntityValueUnion_DefaultCtor_fn = void*(*)(void*);
inline EntityValueUnion_DefaultCtor_fn EntityValueUnion_DefaultCtor() {
    return reinterpret_cast<EntityValueUnion_DefaultCtor_fn>(rsmm::fn_resolve(Sym::EntityValueUnion_DefaultCtor_Pattern));
}

// EntityValueUnion_Destruct  (EntityValueUnion_Destruct)
//   void(void*)
using EntityValueUnion_Destruct_fn = void(*)(void*);
inline EntityValueUnion_Destruct_fn EntityValueUnion_Destruct() {
    return reinterpret_cast<EntityValueUnion_Destruct_fn>(rsmm::fn_resolve(Sym::EntityValueUnion_Destruct_Pattern));
}

// EntityValueUnion_InitAsType  (EntityValueUnion_InitAsType)
//   void(void*, uint32_t)
using EntityValueUnion_InitAsType_fn = void(*)(void*, uint32_t);
inline EntityValueUnion_InitAsType_fn EntityValueUnion_InitAsType() {
    return reinterpret_cast<EntityValueUnion_InitAsType_fn>(rsmm::fn_resolve(Sym::EntityValueUnion_InitAsType_Pattern));
}

// EntityValue_Get  (EntityValue_Get)
//   void(void* valueCtx, oCEntityValueUnion* out, uint32_t crcKey)
using EntityValue_Get_fn = void(*)(void*, void*, uint32_t);
inline EntityValue_Get_fn EntityValue_Get() {
    return reinterpret_cast<EntityValue_Get_fn>(rsmm::fn_resolve(Sym::EntityValue_Get_Pattern));
}

// EntityValue_Lookup  (EntityValue_Lookup)
//   oCEntityValueUnion*(void* store, oCEntityValueUnion* out, uint32_t crcKey)
using EntityValue_Lookup_fn = void*(*)(void*, void*, uint32_t);
inline EntityValue_Lookup_fn EntityValue_Lookup() {
    return reinterpret_cast<EntityValue_Lookup_fn>(rsmm::fn_resolve(Sym::EntityValue_Lookup_Pattern));
}

// Entity_AllocInstance  (Entity_AllocInstance)
//   void*(void* allocator)
using Entity_AllocInstance_fn = void*(*)(void*);
inline Entity_AllocInstance_fn Entity_AllocInstance() {
    return reinterpret_cast<Entity_AllocInstance_fn>(rsmm::fn_resolve(Sym::Entity_AllocInstance_Pattern));
}

// Entity_DispatchHit  (Entity_DispatchHit)
//   void(oCEntity* target, oCEntityHitData* hit)
using Entity_DispatchHit_fn = void(*)(void*, void*);
inline Entity_DispatchHit_fn Entity_DispatchHit() {
    return reinterpret_cast<Entity_DispatchHit_fn>(rsmm::fn_resolve(Sym::Entity_DispatchHit_Pattern));
}

// Entity_FindComponentByType  (Entity_FindComponentByType)
//   oIEntityCpnt*(oCEntitySpawnerGo* go, oCMetaClass* meta)
using Entity_FindComponentByType_fn = void*(*)(void*, void*);
inline Entity_FindComponentByType_fn Entity_FindComponentByType() {
    return reinterpret_cast<Entity_FindComponentByType_fn>(rsmm::fn_resolve(Sym::Entity_FindComponentByType_Pattern));
}

// Entity_FindMagicalObjectComponent  (Entity_FindMagicalObjectComponent)
//   void*(void* instance, void* mo_component_meta)
using Entity_FindMagicalObjectComponent_fn = void*(*)(void*, void*);
inline Entity_FindMagicalObjectComponent_fn Entity_FindMagicalObjectComponent() {
    return reinterpret_cast<Entity_FindMagicalObjectComponent_fn>(rsmm::fn_resolve(Sym::Entity_FindMagicalObjectComponent_Pattern));
}

// Entity_GetComponentByTester  (Entity_GetComponentByTester)
//   void*(void*, void*)
using Entity_GetComponentByTester_fn = void*(*)(void*, void*);
inline Entity_GetComponentByTester_fn Entity_GetComponentByTester() {
    return reinterpret_cast<Entity_GetComponentByTester_fn>(rsmm::fn_resolve(Sym::Entity_GetComponentByTester_Pattern));
}

// Entity_GetComponentFast  (Entity_GetComponentFast)
//   void*(void*, void*, uint32_t)
using Entity_GetComponentFast_fn = void*(*)(void*, void*, uint32_t);
inline Entity_GetComponentFast_fn Entity_GetComponentFast() {
    return reinterpret_cast<Entity_GetComponentFast_fn>(rsmm::fn_resolve(Sym::Entity_GetComponentFast_Pattern));
}

// Entity_GetNetComponent  (Entity_GetNetComponent)
//   void*(oCEntity* entity)
using Entity_GetNetComponent_fn = void*(*)(void*);
inline Entity_GetNetComponent_fn Entity_GetNetComponent() {
    return reinterpret_cast<Entity_GetNetComponent_fn>(rsmm::fn_resolve(Sym::Entity_GetNetComponent_Pattern));
}

// Entity_LookupMagicalObjectComponent  (Entity_LookupMagicalObjectComponent)
//   void*(void* componentStore, void** out, oCEntity* entity)
using Entity_LookupMagicalObjectComponent_fn = void*(*)(void*, void*, void*);
inline Entity_LookupMagicalObjectComponent_fn Entity_LookupMagicalObjectComponent() {
    return reinterpret_cast<Entity_LookupMagicalObjectComponent_fn>(rsmm::fn_resolve(Sym::Entity_LookupMagicalObjectComponent_Pattern));
}

// Entity_ModifyHealth  (Entity_ModifyHealth)
//   void(oCEntity* hero, float delta, oCCustomFlagList* sourceTags)
using Entity_ModifyHealth_fn = void(*)(void*, float, void*);
inline Entity_ModifyHealth_fn Entity_ModifyHealth() {
    return reinterpret_cast<Entity_ModifyHealth_fn>(rsmm::fn_resolve(Sym::Entity_ModifyHealth_Pattern));
}

// Entity_ResolveAttackHits  (Entity_ResolveAttackHits)
//   float(void* attacker, uint hitDefIndex, TargetList* targets, float damageMul, float baseDamage)
using Entity_ResolveAttackHits_fn = float(*)(void*, uint32_t, void*, float, float);
inline Entity_ResolveAttackHits_fn Entity_ResolveAttackHits() {
    return reinterpret_cast<Entity_ResolveAttackHits_fn>(rsmm::fn_resolve(Sym::Entity_ResolveAttackHits_Pattern));
}

// Entry_Ctor  (Entry_Ctor)
//   void(void* base, uint32_t count)
using Entry_Ctor_fn = void(*)(void*, uint32_t);
inline Entry_Ctor_fn Entry_Ctor() {
    return reinterpret_cast<Entry_Ctor_fn>(rsmm::fn_resolve(Sym::Entry_Ctor_Pattern));
}

// Event_LevelUp  (Event_LevelUp)
using Event_LevelUp_fn = void*(*)(void*, void*);
inline Event_LevelUp_fn Event_LevelUp() {
    return reinterpret_cast<Event_LevelUp_fn>(rsmm::fn_resolve(Sym::Event_LevelUp_Pattern));
}

// Event_RunEnd  (Event_RunEnd)
using Event_RunEnd_fn = void*(*)(void*, void*);
inline Event_RunEnd_fn Event_RunEnd() {
    return reinterpret_cast<Event_RunEnd_fn>(rsmm::fn_resolve(Sym::Event_RunEnd_Pattern));
}

// GameModeDefaultDef_PostLoad  (GameModeDefaultDef_PostLoad)
//   bool(void* definition)
using GameModeDefaultDef_PostLoad_fn = uint32_t(*)(void*);
inline GameModeDefaultDef_PostLoad_fn GameModeDefaultDef_PostLoad() {
    return reinterpret_cast<GameModeDefaultDef_PostLoad_fn>(rsmm::fn_resolve(Sym::GameModeDefaultDef_PostLoad_Pattern));
}

// GameModifierDef_PostLoad  (GameModifierDef_PostLoad)
//   bool(void* definition)
using GameModifierDef_PostLoad_fn = uint32_t(*)(void*);
inline GameModifierDef_PostLoad_fn GameModifierDef_PostLoad() {
    return reinterpret_cast<GameModifierDef_PostLoad_fn>(rsmm::fn_resolve(Sym::GameModifierDef_PostLoad_Pattern));
}

// GroupLevelComponent_Ctor  (GroupLevelComponent_Ctor)
//   void*(void* self)
using GroupLevelComponent_Ctor_fn = void*(*)(void*);
inline GroupLevelComponent_Ctor_fn GroupLevelComponent_Ctor() {
    return reinterpret_cast<GroupLevelComponent_Ctor_fn>(rsmm::fn_resolve(Sym::GroupLevelComponent_Ctor_Pattern));
}

// HeroController_Ctor  (HeroController_Ctor)
//   oCDtEntityCpntHeroController*(oCDtEntityCpntHeroController* self)
using HeroController_Ctor_fn = void*(*)(void*);
inline HeroController_Ctor_fn HeroController_Ctor() {
    return reinterpret_cast<HeroController_Ctor_fn>(rsmm::fn_resolve(Sym::HeroController_Ctor_Pattern));
}

// HeroDef_Deserialize  (HeroDef_Deserialize)
//   bool(oCDtHeroDefinition* def, oCBinaryStream* stream)
using HeroDef_Deserialize_fn = uint32_t(*)(void*, void*);
inline HeroDef_Deserialize_fn HeroDef_Deserialize() {
    return reinterpret_cast<HeroDef_Deserialize_fn>(rsmm::fn_resolve(Sym::HeroDef_Deserialize_Pattern));
}

// HeroDef_PostLoad  (HeroDef_PostLoad)
//   bool(void* definition)
using HeroDef_PostLoad_fn = uint32_t(*)(void*);
inline HeroDef_PostLoad_fn HeroDef_PostLoad() {
    return reinterpret_cast<HeroDef_PostLoad_fn>(rsmm::fn_resolve(Sym::HeroDef_PostLoad_Pattern));
}

// HeroProgressionUnlock_IsUnlocked  (HeroProgressionUnlock_IsUnlocked)
//   bool(void* condition_data)
using HeroProgressionUnlock_IsUnlocked_fn = uint32_t(*)(void*);
inline HeroProgressionUnlock_IsUnlocked_fn HeroProgressionUnlock_IsUnlocked() {
    return reinterpret_cast<HeroProgressionUnlock_IsUnlocked_fn>(rsmm::fn_resolve(Sym::HeroProgressionUnlock_IsUnlocked_Pattern));
}

// HeroRankLock_IsUnlocked  (HeroRankLock_IsUnlocked)
//   bool(void* condition_data)
using HeroRankLock_IsUnlocked_fn = uint32_t(*)(void*);
inline HeroRankLock_IsUnlocked_fn HeroRankLock_IsUnlocked() {
    return reinterpret_cast<HeroRankLock_IsUnlocked_fn>(rsmm::fn_resolve(Sym::HeroRankLock_IsUnlocked_Pattern));
}

// HeroStoryUnlock_IsUnlocked  (HeroStoryUnlock_IsUnlocked)
//   bool(void* condition_data)
using HeroStoryUnlock_IsUnlocked_fn = uint32_t(*)(void*);
inline HeroStoryUnlock_IsUnlocked_fn HeroStoryUnlock_IsUnlocked() {
    return reinterpret_cast<HeroStoryUnlock_IsUnlocked_fn>(rsmm::fn_resolve(Sym::HeroStoryUnlock_IsUnlocked_Pattern));
}

// Hero_GainExperience  (Hero_GainExperience)
//   void(void*, void*)
using Hero_GainExperience_fn = void(*)(void*, void*);
inline Hero_GainExperience_fn Hero_GainExperience() {
    return reinterpret_cast<Hero_GainExperience_fn>(rsmm::fn_resolve(Sym::Hero_GainExperience_Pattern));
}

// Hero_GrantMagicalObject  (Hero_GrantMagicalObject)
//   void(oCDtEntityCpntHeroController* hero, void* def, uint16_t count, char dupFlag, void* sourceTags)
using Hero_GrantMagicalObject_fn = void(*)(void*, void*, uint32_t, uint32_t, void*);
inline Hero_GrantMagicalObject_fn Hero_GrantMagicalObject() {
    return reinterpret_cast<Hero_GrantMagicalObject_fn>(rsmm::fn_resolve(Sym::Hero_GrantMagicalObject_Pattern));
}

// IngredientDef_PostLoad  (IngredientDef_PostLoad)
//   bool(void* definition)
using IngredientDef_PostLoad_fn = uint32_t(*)(void*);
inline IngredientDef_PostLoad_fn IngredientDef_PostLoad() {
    return reinterpret_cast<IngredientDef_PostLoad_fn>(rsmm::fn_resolve(Sym::IngredientDef_PostLoad_Pattern));
}

// LobbyAttributes_Parse  (LobbyAttributes_Parse)
//   void*(void* self, StringDesc* blob)
using LobbyAttributes_Parse_fn = void*(*)(void*, void*);
inline LobbyAttributes_Parse_fn LobbyAttributes_Parse() {
    return reinterpret_cast<LobbyAttributes_Parse_fn>(rsmm::fn_resolve(Sym::LobbyAttributes_Parse_Pattern));
}

// LobbyAttributes_Serialize  (LobbyAttributes_Serialize)
//   void*(void* out, void* member)
using LobbyAttributes_Serialize_fn = void*(*)(void*, void*);
inline LobbyAttributes_Serialize_fn LobbyAttributes_Serialize() {
    return reinterpret_cast<LobbyAttributes_Serialize_fn>(rsmm::fn_resolve(Sym::LobbyAttributes_Serialize_Pattern));
}

// MagicalObjectPool_Grow  (MagicalObjectPool_Grow)
//   void(void* pool_plus_0x10, uint32_t count, uint32_t by)
using MagicalObjectPool_Grow_fn = void(*)(void*, uint32_t, uint32_t);
inline MagicalObjectPool_Grow_fn MagicalObjectPool_Grow() {
    return reinterpret_cast<MagicalObjectPool_Grow_fn>(rsmm::fn_resolve(Sym::MagicalObjectPool_Grow_Pattern));
}

// MagicalObjectPool_SourceLookup  (MagicalObjectPool_SourceLookup)
//   void*(void* pool, void* out, void* id)
using MagicalObjectPool_SourceLookup_fn = void*(*)(void*, void*, void*);
inline MagicalObjectPool_SourceLookup_fn MagicalObjectPool_SourceLookup() {
    return reinterpret_cast<MagicalObjectPool_SourceLookup_fn>(rsmm::fn_resolve(Sym::MagicalObjectPool_SourceLookup_Pattern));
}

// MagicalObject_RegisterInstance  (MagicalObject_RegisterInstance)
//   void(oCDtEntityCpntHeroController* hero, void* instance, char addToActive)
using MagicalObject_RegisterInstance_fn = void(*)(void*, void*, uint32_t);
inline MagicalObject_RegisterInstance_fn MagicalObject_RegisterInstance() {
    return reinterpret_cast<MagicalObject_RegisterInstance_fn>(rsmm::fn_resolve(Sym::MagicalObject_RegisterInstance_Pattern));
}

// MagicalObject_SpawnAllObjects  (MagicalObject_SpawnAllObjects)
//   void(void* pool, void* scene)
using MagicalObject_SpawnAllObjects_fn = void(*)(void*, void*);
inline MagicalObject_SpawnAllObjects_fn MagicalObject_SpawnAllObjects() {
    return reinterpret_cast<MagicalObject_SpawnAllObjects_fn>(rsmm::fn_resolve(Sym::MagicalObject_SpawnAllObjects_Pattern));
}

// MapDef_PostLoad  (MapDef_PostLoad)
//   bool(void* definition)
using MapDef_PostLoad_fn = uint32_t(*)(void*);
inline MapDef_PostLoad_fn MapDef_PostLoad() {
    return reinterpret_cast<MapDef_PostLoad_fn>(rsmm::fn_resolve(Sym::MapDef_PostLoad_Pattern));
}

// MelodyDef_PostLoad  (MelodyDef_PostLoad)
//   bool(void* definition)
using MelodyDef_PostLoad_fn = uint32_t(*)(void*);
inline MelodyDef_PostLoad_fn MelodyDef_PostLoad() {
    return reinterpret_cast<MelodyDef_PostLoad_fn>(rsmm::fn_resolve(Sym::MelodyDef_PostLoad_Pattern));
}

// ModifierEvent_Ctor  (ModifierEvent_Ctor)
//   void*(void* buf, void* valueDef)
using ModifierEvent_Ctor_fn = void*(*)(void*, void*);
inline ModifierEvent_Ctor_fn ModifierEvent_Ctor() {
    return reinterpret_cast<ModifierEvent_Ctor_fn>(rsmm::fn_resolve(Sym::ModifierEvent_Ctor_Pattern));
}

// NamedEvent_ChannelMap_Find  (NamedEvent_ChannelMap_Find)
//   iter*(void* channel_map, iter* out, uint32_t* event_id)
using NamedEvent_ChannelMap_Find_fn = void*(*)(void*, void*, void*);
inline NamedEvent_ChannelMap_Find_fn NamedEvent_ChannelMap_Find() {
    return reinterpret_cast<NamedEvent_ChannelMap_Find_fn>(rsmm::fn_resolve(Sym::NamedEvent_ChannelMap_Find_Pattern));
}

// NamedEvent_Delete  (NamedEvent_Delete)
//   void(oCGameNamedEvent* ev)
using NamedEvent_Delete_fn = void(*)(void*);
inline NamedEvent_Delete_fn NamedEvent_Delete() {
    return reinterpret_cast<NamedEvent_Delete_fn>(rsmm::fn_resolve(Sym::NamedEvent_Delete_Pattern));
}

// NamedEvent_Dispatch  (NamedEvent_Dispatch)
//   void(void* dispatcher, oCGameNamedEvent* ev)
using NamedEvent_Dispatch_fn = void(*)(void*, void*);
inline NamedEvent_Dispatch_fn NamedEvent_Dispatch() {
    return reinterpret_cast<NamedEvent_Dispatch_fn>(rsmm::fn_resolve(Sym::NamedEvent_Dispatch_Pattern));
}

// NamedEvent_GiveMagicalObject_Ctor  (NamedEvent_GiveMagicalObject_Ctor)
//   oe::dt::NamedEventGiveMagicalObject*(void* buf)
using NamedEvent_GiveMagicalObject_Ctor_fn = void*(*)(void*);
inline NamedEvent_GiveMagicalObject_Ctor_fn NamedEvent_GiveMagicalObject_Ctor() {
    return reinterpret_cast<NamedEvent_GiveMagicalObject_Ctor_fn>(rsmm::fn_resolve(Sym::NamedEvent_GiveMagicalObject_Ctor_Pattern));
}

// NamedEvent_HeroSubscribeAll  (NamedEvent_HeroSubscribeAll)
//   void(oCEntity* hero)
using NamedEvent_HeroSubscribeAll_fn = void(*)(void*);
inline NamedEvent_HeroSubscribeAll_fn NamedEvent_HeroSubscribeAll() {
    return reinterpret_cast<NamedEvent_HeroSubscribeAll_fn>(rsmm::fn_resolve(Sym::NamedEvent_HeroSubscribeAll_Pattern));
}

// NamedEvent_Id_FromCrc  (NamedEvent_Id_FromCrc)
//   uint32_t(uint32_t ns, uint32_t name_crc)
using NamedEvent_Id_FromCrc_fn = uint32_t(*)(uint32_t, uint32_t);
inline NamedEvent_Id_FromCrc_fn NamedEvent_Id_FromCrc() {
    return reinterpret_cast<NamedEvent_Id_FromCrc_fn>(rsmm::fn_resolve(Sym::NamedEvent_Id_FromCrc_Pattern));
}

// NamedEvent_NetSend  (NamedEvent_NetSend)
//   void(void* net_event_cpnt, oCGameNamedEvent* ev)
using NamedEvent_NetSend_fn = void(*)(void*, void*);
inline NamedEvent_NetSend_fn NamedEvent_NetSend() {
    return reinterpret_cast<NamedEvent_NetSend_fn>(rsmm::fn_resolve(Sym::NamedEvent_NetSend_Pattern));
}

// NamedEvent_NetSendToPeer  (NamedEvent_NetSendToPeer)
//   void(void* net_event_cpnt, oCGameNamedEvent* ev, uint64_t* peer_session)
using NamedEvent_NetSendToPeer_fn = void(*)(void*, void*, void*);
inline NamedEvent_NetSendToPeer_fn NamedEvent_NetSendToPeer() {
    return reinterpret_cast<NamedEvent_NetSendToPeer_fn>(rsmm::fn_resolve(Sym::NamedEvent_NetSendToPeer_Pattern));
}

// Netcode_Channel_LookupById  (Netcode_Channel_LookupById)
//   iter*(void* channel_map, iter* out, uint32_t* event_id)
using Netcode_Channel_LookupById_fn = void*(*)(void*, void*, void*);
inline Netcode_Channel_LookupById_fn Netcode_Channel_LookupById() {
    return reinterpret_cast<Netcode_Channel_LookupById_fn>(rsmm::fn_resolve(Sym::Netcode_Channel_LookupById_Pattern));
}

// Netcode_Channel_Unsubscribe  (Netcode_Channel_Unsubscribe)
//   void(void* node_plus_8, void** sub_slot)
using Netcode_Channel_Unsubscribe_fn = void(*)(void*, void*);
inline Netcode_Channel_Unsubscribe_fn Netcode_Channel_Unsubscribe() {
    return reinterpret_cast<Netcode_Channel_Unsubscribe_fn>(rsmm::fn_resolve(Sym::Netcode_Channel_Unsubscribe_Pattern));
}

// Netcode_EntityReplSetup  (Netcode_EntityReplSetup)
//   void(void* replContext)
using Netcode_EntityReplSetup_fn = void(*)(void*);
inline Netcode_EntityReplSetup_fn Netcode_EntityReplSetup() {
    return reinterpret_cast<Netcode_EntityReplSetup_fn>(rsmm::fn_resolve(Sym::Netcode_EntityReplSetup_Pattern));
}

// ProjectileAttack_BeginAttack  (ProjectileAttack_BeginAttack)
//   void(void* projectile_attack_cpnt)
using ProjectileAttack_BeginAttack_fn = void(*)(void*);
inline ProjectileAttack_BeginAttack_fn ProjectileAttack_BeginAttack() {
    return reinterpret_cast<ProjectileAttack_BeginAttack_fn>(rsmm::fn_resolve(Sym::ProjectileAttack_BeginAttack_Pattern));
}

// Registry_EnumInstances  (Registry_EnumInstances)
//   void*(void* unused, void* out3, void** classDescPtr)
using Registry_EnumInstances_fn = void*(*)(void*, void*, void*);
inline Registry_EnumInstances_fn Registry_EnumInstances() {
    return reinterpret_cast<Registry_EnumInstances_fn>(rsmm::fn_resolve(Sym::Registry_EnumInstances_Pattern));
}

// Registry_UnregisterInstance  (Registry_UnregisterInstance)
//   void(void*)
using Registry_UnregisterInstance_fn = void(*)(void*);
inline Registry_UnregisterInstance_fn Registry_UnregisterInstance() {
    return reinterpret_cast<Registry_UnregisterInstance_fn>(rsmm::fn_resolve(Sym::Registry_UnregisterInstance_Pattern));
}

// Resource_LookupByPath  (Resource_LookupByPath)
//   void*(const char* decoded_path, void*, void*, void*)
using Resource_LookupByPath_fn = void*(*)(const char*, void*, void*, void*);
inline Resource_LookupByPath_fn Resource_LookupByPath() {
    return reinterpret_cast<Resource_LookupByPath_fn>(rsmm::fn_resolve(Sym::Resource_LookupByPath_Pattern));
}

// SharedRef_Release  (SharedRef_Release)
//   void(void*)
using SharedRef_Release_fn = void(*)(void*);
inline SharedRef_Release_fn SharedRef_Release() {
    return reinterpret_cast<SharedRef_Release_fn>(rsmm::fn_resolve(Sym::SharedRef_Release_Pattern));
}

// SkinGrid_Populate  (SkinGrid_Populate)
//   void(void* ctx, void* arg)
using SkinGrid_Populate_fn = void(*)(void*, void*);
inline SkinGrid_Populate_fn SkinGrid_Populate() {
    return reinterpret_cast<SkinGrid_Populate_fn>(rsmm::fn_resolve(Sym::SkinGrid_Populate_Pattern));
}

// String_Assign  (String_Assign)
//   void(void* dst_slot, const StringDesc* src)
using String_Assign_fn = void(*)(void*, const void*);
inline String_Assign_fn String_Assign() {
    return reinterpret_cast<String_Assign_fn>(rsmm::fn_resolve(Sym::String_Assign_Pattern));
}

// UiButton_InputPoll  (UiButton_InputPoll)
//   void(ButtonUiCpntArray* cpnts)
using UiButton_InputPoll_fn = void(*)(void*);
inline UiButton_InputPoll_fn UiButton_InputPoll() {
    return reinterpret_cast<UiButton_InputPoll_fn>(rsmm::fn_resolve(Sym::UiButton_InputPoll_Pattern));
}

// UiButton_PressCommit  (UiButton_PressCommit)
//   void(oCUINavigableZoneDesc* widget)
using UiButton_PressCommit_fn = void(*)(void*);
inline UiButton_PressCommit_fn UiButton_PressCommit() {
    return reinterpret_cast<UiButton_PressCommit_fn>(rsmm::fn_resolve(Sym::UiButton_PressCommit_Pattern));
}

// Vector_Grow  (Vector_Grow)
//   void(void* vec, void* /*dead RDX*/, uint32_t new_cap /*R8*/)
using Vector_Grow_fn = void(*)(void*, uint64_t, uint32_t);
inline Vector_Grow_fn Vector_Grow() {
    return reinterpret_cast<Vector_Grow_fn>(rsmm::fn_resolve(Sym::Vector_Grow_Pattern));
}

// XpComponent_GetMaxLevel  (XpComponent_GetMaxLevel)
//   uint32_t(void*)
using XpComponent_GetMaxLevel_fn = uint32_t(*)(void*);
inline XpComponent_GetMaxLevel_fn XpComponent_GetMaxLevel() {
    return reinterpret_cast<XpComponent_GetMaxLevel_fn>(rsmm::fn_resolve(Sym::XpComponent_GetMaxLevel_Pattern));
}

// XpComponent_IsMaxLevel  (XpComponent_IsMaxLevel)
//   bool(void*)
using XpComponent_IsMaxLevel_fn = uint32_t(*)(void*);
inline XpComponent_IsMaxLevel_fn XpComponent_IsMaxLevel() {
    return reinterpret_cast<XpComponent_IsMaxLevel_fn>(rsmm::fn_resolve(Sym::XpComponent_IsMaxLevel_Pattern));
}

// XpComponent_SetLevel  (XpComponent_SetLevel)
//   void(void*, uint32_t)
using XpComponent_SetLevel_fn = void(*)(void*, uint32_t);
inline XpComponent_SetLevel_fn XpComponent_SetLevel() {
    return reinterpret_cast<XpComponent_SetLevel_fn>(rsmm::fn_resolve(Sym::XpComponent_SetLevel_Pattern));
}

// XpComponent_SetXp  (XpComponent_SetXp)
//   void(void*, uint32_t)
using XpComponent_SetXp_fn = void(*)(void*, uint32_t);
inline XpComponent_SetXp_fn XpComponent_SetXp() {
    return reinterpret_cast<XpComponent_SetXp_fn>(rsmm::fn_resolve(Sym::XpComponent_SetXp_Pattern));
}

// XpComponent_XpForLevel  (XpComponent_XpForLevel)
//   uint32_t(void*, uint32_t)
using XpComponent_XpForLevel_fn = uint32_t(*)(void*, uint32_t);
inline XpComponent_XpForLevel_fn XpComponent_XpForLevel() {
    return reinterpret_cast<XpComponent_XpForLevel_fn>(rsmm::fn_resolve(Sym::XpComponent_XpForLevel_Pattern));
}

}  // namespace engine
