// GENERATED by `rsmm symbols gen` from data/symbols.json — DO NOT EDIT.
// Preferred-base addresses; the loader rebases by image-base delta and,
// for `pattern`-backed symbols, re-resolves via data/function_patterns.json.
#pragma once
#include <cstdint>

namespace Sym {
constexpr std::uintptr_t kPreferredBase = 0x140000000ull;

// --- enemies ---
constexpr std::uintptr_t EnemyCamp_Stage3Filter = 0x140323830ull;
constexpr const char* EnemyCamp_Stage3Filter_Pattern = "EnemyCamp_Stage3Filter";
constexpr std::uintptr_t EnemyCamp_TierSelector = 0x140332850ull;
constexpr const char* EnemyCamp_TierSelector_Pattern = "EnemyCamp_TierSelector";
constexpr std::uintptr_t EnemyCamp_TribeEntryBuilder = 0x1403343a0ull;
constexpr const char* EnemyCamp_TribeEntryBuilder_Pattern = "EnemyCamp_TribeEntryBuilder";
constexpr std::uintptr_t EnemyDef_PostLoad = 0x140324320ull;
constexpr const char* EnemyDef_PostLoad_Pattern = "EnemyDef_PostLoad";
constexpr std::uintptr_t EnemyDefinition_ctor = 0x1401dea90ull;
constexpr const char* EnemyDefinition_ctor_Pattern = "EnemyDefinition_ctor";
constexpr std::uintptr_t EnemyTribeDef_PostLoad = 0x140325540ull;
constexpr const char* EnemyTribeDef_PostLoad_Pattern = "EnemyTribeDef_PostLoad";
constexpr std::uintptr_t EnemyTribeDefinition_ctor = 0x1400c5260ull;
constexpr const char* EnemyTribeDefinition_ctor_Pattern = "EnemyTribeDefinition_ctor";
constexpr std::uintptr_t Enemy_RuntimeSpawnPicker = 0x140364360ull;
constexpr const char* Enemy_RuntimeSpawnPicker_Pattern = "Enemy_RuntimeSpawnPicker";
constexpr std::uintptr_t MapCtx_DistributeEnemyCampTiers = 0x1401ebd00ull;
constexpr const char* MapCtx_DistributeEnemyCampTiers_Pattern = "MapCtx_DistributeEnemyCampTiers";

// --- engine ---
constexpr std::uintptr_t Entry_Ctor = 0x140219060ull;
constexpr const char* Entry_Ctor_Pattern = "Entry_Ctor";
constexpr std::uintptr_t Format_String = 0x1402092a0ull;
constexpr const char* Format_String_Pattern = "Format_String";
constexpr std::uintptr_t LevelLoad_Orchestrator = 0x1402928c0ull;
constexpr const char* LevelLoad_Orchestrator_Pattern = "LevelLoad_Orchestrator";
constexpr std::uintptr_t String_Assign = 0x140540ff0ull;
constexpr const char* String_Assign_Pattern = "String_Assign";
constexpr std::uintptr_t Vector_Grow = 0x140154c20ull;
constexpr const char* Vector_Grow_Pattern = "Vector_Grow";

// --- engine-core ---
constexpr std::uintptr_t ClassRegistry_FindByKey = 0x140523a10ull;
constexpr const char* ClassRegistry_FindByKey_Pattern = "ClassRegistry_FindByKey";
constexpr std::uintptr_t ClassRegistry_Global = 0x141436690ull;
constexpr std::uintptr_t CustomFlagFilter_Serialize = 0x140189830ull;
constexpr const char* CustomFlagFilter_Serialize_Pattern = "CustomFlagFilter_Serialize";
constexpr std::uintptr_t CustomFlagList_Serialize = 0x140681e60ull;
constexpr const char* CustomFlagList_Serialize_Pattern = "CustomFlagList_Serialize";
constexpr std::uintptr_t GameScene_FindContextByTester = 0x140684660ull;
constexpr const char* GameScene_FindContextByTester_Pattern = "GameScene_FindContextByTester";
constexpr std::uintptr_t Profiler_GetThreadScopeStack = 0x14053a660ull;
constexpr const char* Profiler_GetThreadScopeStack_Pattern = "Profiler_GetThreadScopeStack";
constexpr std::uintptr_t Property_EvaluateByGuid = 0x1406c3720ull;
constexpr const char* Property_EvaluateByGuid_Pattern = "Property_EvaluateByGuid";
constexpr std::uintptr_t ResourceRef_Serialize = 0x1401cbba0ull;
constexpr const char* ResourceRef_Serialize_Pattern = "ResourceRef_Serialize";
constexpr std::uintptr_t Serializer_GetClassVersion = 0x140514570ull;
constexpr const char* Serializer_GetClassVersion_Pattern = "Serializer_GetClassVersion";
constexpr std::uintptr_t Serializer_ReadPolyPtrVector = 0x14020e000ull;
constexpr const char* Serializer_ReadPolyPtrVector_Pattern = "Serializer_ReadPolyPtrVector";
constexpr std::uintptr_t ServiceRegistry_Global = 0x14146f740ull;
constexpr std::uintptr_t StringVector_Serialize = 0x140684f30ull;
constexpr const char* StringVector_Serialize_Pattern = "StringVector_Serialize";

// --- entity ---
constexpr std::uintptr_t EntityPool_AllocNode = 0x140690e50ull;
constexpr const char* EntityPool_AllocNode_Pattern = "EntityPool_AllocNode";
constexpr std::uintptr_t EntitySpawner_InstantiateRecord = 0x140730f80ull;
constexpr const char* EntitySpawner_InstantiateRecord_Pattern = "EntitySpawner_InstantiateRecord";
constexpr std::uintptr_t EntitySpawner_SpawnOne = 0x140730150ull;
constexpr const char* EntitySpawner_SpawnOne_Pattern = "EntitySpawner_SpawnOne";
constexpr std::uintptr_t EntityStore_CreateEntity = 0x1406f5dc0ull;
constexpr const char* EntityStore_CreateEntity_Pattern = "EntityStore_CreateEntity";
constexpr std::uintptr_t EntityValueEntry_Ctor = 0x140747120ull;
constexpr const char* EntityValueEntry_Ctor_Pattern = "EntityValueEntry_Ctor";
constexpr std::uintptr_t EntityValueOverride_Alloc = 0x140770290ull;
constexpr const char* EntityValueOverride_Alloc_Pattern = "EntityValueOverride_Alloc";
constexpr std::uintptr_t EntityValueStore_ApplyModifierEvent = 0x14074b2f0ull;
constexpr const char* EntityValueStore_ApplyModifierEvent_Pattern = "EntityValueStore_ApplyModifierEvent";
constexpr std::uintptr_t EntityValueStore_InitBaseValues = 0x140747f20ull;
constexpr const char* EntityValueStore_InitBaseValues_Pattern = "EntityValueStore_InitBaseValues";
constexpr std::uintptr_t EntityValueStore_Recompute = 0x140749a90ull;
constexpr const char* EntityValueStore_Recompute_Pattern = "EntityValueStore_Recompute";
constexpr std::uintptr_t EntityValueUnion_Compare = 0x14082ceb0ull;
constexpr const char* EntityValueUnion_Compare_Pattern = "EntityValueUnion_Compare";
constexpr std::uintptr_t EntityValueUnion_CopyAssign = 0x14082b1d0ull;
constexpr const char* EntityValueUnion_CopyAssign_Pattern = "EntityValueUnion_CopyAssign";
constexpr std::uintptr_t EntityValueUnion_DefaultCtor = 0x14082aa60ull;
constexpr const char* EntityValueUnion_DefaultCtor_Pattern = "EntityValueUnion_DefaultCtor";
constexpr std::uintptr_t EntityValueUnion_Destruct = 0x14082dae0ull;
constexpr const char* EntityValueUnion_Destruct_Pattern = "EntityValueUnion_Destruct";
constexpr std::uintptr_t EntityValueUnion_InitAsType = 0x14082d670ull;
constexpr const char* EntityValueUnion_InitAsType_Pattern = "EntityValueUnion_InitAsType";
constexpr std::uintptr_t EntityValue_Get = 0x1403c7fa0ull;
constexpr const char* EntityValue_Get_Pattern = "EntityValue_Get";
constexpr std::uintptr_t EntityValue_Lookup = 0x140749260ull;
constexpr const char* EntityValue_Lookup_Pattern = "EntityValue_Lookup";
constexpr std::uintptr_t Entity_AllocInstance = 0x1406a8d80ull;
constexpr const char* Entity_AllocInstance_Pattern = "Entity_AllocInstance";
constexpr std::uintptr_t Entity_DispatchHit = 0x1406e3ce0ull;
constexpr const char* Entity_DispatchHit_Pattern = "Entity_DispatchHit";
constexpr std::uintptr_t Entity_FindComponentByType = 0x1406e3210ull;
constexpr const char* Entity_FindComponentByType_Pattern = "Entity_FindComponentByType";
constexpr std::uintptr_t Entity_FindMagicalObjectComponent = 0x1406fb8a2ull;
constexpr const char* Entity_FindMagicalObjectComponent_Pattern = "Entity_FindMagicalObjectComponent";
constexpr std::uintptr_t Entity_GainHealthHandler = 0x140399d00ull;
constexpr const char* Entity_GainHealthHandler_Pattern = "Entity_GainHealthHandler";
constexpr std::uintptr_t Entity_GetComponentByTester = 0x1406e3210ull;
constexpr const char* Entity_GetComponentByTester_Pattern = "Entity_GetComponentByTester";
constexpr std::uintptr_t Entity_GetComponentFast = 0x1406e31a0ull;
constexpr const char* Entity_GetComponentFast_Pattern = "Entity_GetComponentFast";
constexpr std::uintptr_t Entity_ModifyHealth = 0x14039a320ull;
constexpr const char* Entity_ModifyHealth_Pattern = "Entity_ModifyHealth";
constexpr std::uintptr_t Entity_ResolveAttackHits = 0x1403dd540ull;
constexpr const char* Entity_ResolveAttackHits_Pattern = "Entity_ResolveAttackHits";
constexpr std::uintptr_t HeroController_Ctor = 0x14038ec30ull;
constexpr const char* HeroController_Ctor_Pattern = "HeroController_Ctor";
constexpr std::uintptr_t HeroController_HudMirror_Ctor = 0x1403b3c70ull;
constexpr const char* HeroController_HudMirror_Ctor_Pattern = "HeroController_HudMirror_Ctor";
constexpr std::uintptr_t MapCtx_LinkPairedSpawners = 0x1401ef131ull;
constexpr const char* MapCtx_LinkPairedSpawners_Pattern = "MapCtx_LinkPairedSpawners";
constexpr std::uintptr_t ModifierEvent_Ctor = 0x140389fb0ull;
constexpr const char* ModifierEvent_Ctor_Pattern = "ModifierEvent_Ctor";
constexpr std::uintptr_t g_MagicalObjectComponentMeta = 0x141470768ull;
constexpr std::uintptr_t oCCustomFlagList_vftable = 0x140f01650ull;
constexpr std::uintptr_t oCEntityHitData_vftable = 0x140f137d8ull;
constexpr std::uintptr_t oCEntityValueUnion_vftable = 0x140f95008ull;
constexpr std::uintptr_t oCGameEventNetworkModifier_vftable = 0x140f322d0ull;

// --- entity-values ---
constexpr std::uintptr_t EntityValueRegistry_RegisterAll = 0x1401da350ull;
constexpr const char* EntityValueRegistry_RegisterAll_Pattern = "EntityValueRegistry_RegisterAll";

// --- event ---
constexpr std::uintptr_t Analytics_SubmitNamedEvent = 0x1401fad70ull;
constexpr const char* Analytics_SubmitNamedEvent_Pattern = "Analytics_SubmitNamedEvent";
constexpr std::uintptr_t Crc32_TableInit = 0x14051ef30ull;
constexpr const char* Crc32_TableInit_Pattern = "Crc32_TableInit";
constexpr std::uintptr_t EventQueue_Drain = 0x14067be70ull;
constexpr const char* EventQueue_Drain_Pattern = "EventQueue_Drain";
constexpr std::uintptr_t Event_LevelUp = 0x1401f6bf0ull;
constexpr const char* Event_LevelUp_Pattern = "Event_LevelUp";
constexpr std::uintptr_t Event_RunEnd = 0x1401f59c0ull;
constexpr const char* Event_RunEnd_Pattern = "Event_RunEnd";
constexpr std::uintptr_t Id_HashString = 0x14033f7a0ull;
constexpr const char* Id_HashString_Pattern = "Id_HashString";
constexpr std::uintptr_t NamedEvent_ChannelMap_Find = 0x14066dc10ull;
constexpr const char* NamedEvent_ChannelMap_Find_Pattern = "NamedEvent_ChannelMap_Find";
constexpr std::uintptr_t NamedEvent_Delete = 0x1401273b0ull;
constexpr const char* NamedEvent_Delete_Pattern = "NamedEvent_Delete";
constexpr std::uintptr_t NamedEvent_Dispatch = 0x14066b6b0ull;
constexpr const char* NamedEvent_Dispatch_Pattern = "NamedEvent_Dispatch";
constexpr std::uintptr_t NamedEvent_EmitNetworkDamageFromHit = 0x140743a00ull;
constexpr const char* NamedEvent_EmitNetworkDamageFromHit_Pattern = "NamedEvent_EmitNetworkDamageFromHit";
constexpr std::uintptr_t NamedEvent_GiveMagicalObject_Ctor = 0x14030fd30ull;
constexpr const char* NamedEvent_GiveMagicalObject_Ctor_Pattern = "NamedEvent_GiveMagicalObject_Ctor";
constexpr std::uintptr_t NamedEvent_HeroSubscribeAll = 0x140391860ull;
constexpr const char* NamedEvent_HeroSubscribeAll_Pattern = "NamedEvent_HeroSubscribeAll";
constexpr std::uintptr_t NamedEvent_HeroUnsubscribeAll = 0x1403a2d00ull;
constexpr const char* NamedEvent_HeroUnsubscribeAll_Pattern = "NamedEvent_HeroUnsubscribeAll";
constexpr std::uintptr_t NamedEvent_Id_FromCrc = 0x140536820ull;
constexpr const char* NamedEvent_Id_FromCrc_Pattern = "NamedEvent_Id_FromCrc";
constexpr std::uintptr_t NamedEvent_NetSend = 0x14073d730ull;
constexpr const char* NamedEvent_NetSend_Pattern = "NamedEvent_NetSend";
constexpr std::uintptr_t NamedEvent_NetSendToPeer = 0x1407216c0ull;
constexpr const char* NamedEvent_NetSendToPeer_Pattern = "NamedEvent_NetSendToPeer";

// --- hero ---
constexpr std::uintptr_t Hero_GainExperience = 0x1402e2f00ull;
constexpr const char* Hero_GainExperience_Pattern = "Hero_GainExperience";
constexpr std::uintptr_t XpComponent_SetLevel = 0x1402e3190ull;
constexpr const char* XpComponent_SetLevel_Pattern = "XpComponent_SetLevel";
constexpr std::uintptr_t XpComponent_SetXp = 0x1402e3630ull;
constexpr const char* XpComponent_SetXp_Pattern = "XpComponent_SetXp";
constexpr std::uintptr_t XpComponent_TypeTester = 0x141476e00ull;
constexpr std::uintptr_t XpComponent_vftable = 0x140f23200ull;

// --- heroes ---
constexpr std::uintptr_t HeroDef_LoadBaseEntity = 0x140329660ull;
constexpr const char* HeroDef_LoadBaseEntity_Pattern = "HeroDef_LoadBaseEntity";
constexpr std::uintptr_t HeroDef_LoadSkinEntity = 0x14028e5f0ull;
constexpr const char* HeroDef_LoadSkinEntity_Pattern = "HeroDef_LoadSkinEntity";

// --- items ---
constexpr std::uintptr_t Entity_GiveHandler = 0x1403c7560ull;
constexpr const char* Entity_GiveHandler_Pattern = "Entity_GiveHandler";
constexpr std::uintptr_t Entity_LookupMagicalObjectComponent = 0x1406e3280ull;
constexpr const char* Entity_LookupMagicalObjectComponent_Pattern = "Entity_LookupMagicalObjectComponent";
constexpr std::uintptr_t Hero_GrantMagicalObject = 0x140397aa0ull;
constexpr const char* Hero_GrantMagicalObject_Pattern = "Hero_GrantMagicalObject";
constexpr std::uintptr_t InitialLoading_SpawnMagicalObjects = 0x140265440ull;
constexpr const char* InitialLoading_SpawnMagicalObjects_Pattern = "InitialLoading_SpawnMagicalObjects";
constexpr std::uintptr_t MagicalObjectPool_Grow = 0x140156de0ull;
constexpr const char* MagicalObjectPool_Grow_Pattern = "MagicalObjectPool_Grow";
constexpr std::uintptr_t MagicalObjectPool_SourceLookup = 0x14025e3e0ull;
constexpr const char* MagicalObjectPool_SourceLookup_Pattern = "MagicalObjectPool_SourceLookup";
constexpr std::uintptr_t MagicalObject_RegisterInstance = 0x1403aae40ull;
constexpr const char* MagicalObject_RegisterInstance_Pattern = "MagicalObject_RegisterInstance";
constexpr std::uintptr_t MagicalObject_SpawnAllObjects = 0x14025da20ull;
constexpr const char* MagicalObject_SpawnAllObjects_Pattern = "MagicalObject_SpawnAllObjects.parent";
constexpr std::uintptr_t MagicalObject_SpawnContainingFunc = 0x14025d9b0ull;
constexpr const char* MagicalObject_SpawnContainingFunc_Pattern = "MagicalObject_SpawnContainingFunc";
constexpr std::uintptr_t g_MagicalObjectPool = 0x14143cc18ull;

// --- library ---
constexpr std::uintptr_t Definition_DeserializeBase = 0x140310180ull;
constexpr const char* Definition_DeserializeBase_Pattern = "Definition_DeserializeBase";
constexpr std::uintptr_t GameModifierDef_RegisterAssetLoader = 0x1403260b0ull;
constexpr const char* GameModifierDef_RegisterAssetLoader_Pattern = "GameModifierDef_RegisterAssetLoader";
constexpr std::uintptr_t GoPtrOwnerRelay_ForwardCall = 0x14066bf00ull;
constexpr const char* GoPtrOwnerRelay_ForwardCall_Pattern = "GoPtrOwnerRelay_ForwardCall";
constexpr std::uintptr_t GoPtrOwnerRelay_ForwardGet = 0x14066be70ull;
constexpr const char* GoPtrOwnerRelay_ForwardGet_Pattern = "GoPtrOwnerRelay_ForwardGet";
constexpr std::uintptr_t GoPtrOwnerRelay_ForwardSet = 0x14066bec0ull;
constexpr const char* GoPtrOwnerRelay_ForwardSet_Pattern = "GoPtrOwnerRelay_ForwardSet";
constexpr std::uintptr_t HasGameModifierStateMachine_Register = 0x140197780ull;
constexpr const char* HasGameModifierStateMachine_Register_Pattern = "HasGameModifierStateMachine_Register";
constexpr std::uintptr_t Library_AchievementDefinition_vftable = 0x1414113b0ull;
constexpr std::uintptr_t Library_ChallengeDefinition_vftable = 0x141413010ull;
constexpr std::uintptr_t Library_DreamShardDefinition_vftable = 0x141411050ull;
constexpr std::uintptr_t Library_EnemyCampDifficultyDefinition_vftable = 0x141411710ull;
constexpr std::uintptr_t Library_EnemyCampTierDefinition_vftable = 0x141411560ull;
constexpr std::uintptr_t Library_EnemyDefinition_vftable = 0x1414118c0ull;
constexpr std::uintptr_t Library_EnemyTribeDefinition_vftable = 0x141411200ull;
constexpr std::uintptr_t Library_EntitySettingsResource_vftable = 0x141470950ull;
constexpr std::uintptr_t Library_GameModifierDefinition_vftable = 0x141411b50ull;
constexpr std::uintptr_t Library_IngredientDefinition_vftable = 0x141412c50ull;
constexpr std::uintptr_t Library_MapDefinition_vftable = 0x141412520ull;
constexpr std::uintptr_t Library_MelodyDefinition_vftable = 0x1414129c0ull;
constexpr std::uintptr_t Library_RewardDefinition_vftable = 0x141412e00ull;
constexpr std::uintptr_t Library_TileDefinition_vftable = 0x141412080ull;
constexpr std::uintptr_t Library_VersionDefinition_vftable = 0x141412300ull;
constexpr std::uintptr_t MapDef_RegisterAssetLoader = 0x140323350ull;
constexpr const char* MapDef_RegisterAssetLoader_Pattern = "MapDef_RegisterAssetLoader";
constexpr std::uintptr_t Mem_Alloc16Zeroed = 0x14050d5c0ull;
constexpr const char* Mem_Alloc16Zeroed_Pattern = "Mem_Alloc16Zeroed";
constexpr std::uintptr_t PtrVector_Resize = 0x140155230ull;
constexpr const char* PtrVector_Resize_Pattern = "PtrVector_Resize";
constexpr std::uintptr_t Registry_EnemyDefinition_desc = 0x141470208ull;
constexpr std::uintptr_t Registry_EnemyTribeDefinition_desc = 0x14146f938ull;
constexpr std::uintptr_t RewardDef_RegisterAssetLoader = 0x140324460ull;
constexpr const char* RewardDef_RegisterAssetLoader_Pattern = "RewardDef_RegisterAssetLoader";
constexpr std::uintptr_t Rt_FailFast = 0x140cc7e04ull;
constexpr const char* Rt_FailFast_Pattern = "Rt_FailFast";
constexpr std::uintptr_t SharedRef_AddRefCopy = 0x1401663a0ull;
constexpr const char* SharedRef_AddRefCopy_Pattern = "SharedRef_AddRefCopy";
constexpr std::uintptr_t SharedRef_AddRefCopy_b = 0x14021e390ull;
constexpr const char* SharedRef_AddRefCopy_b_Pattern = "SharedRef_AddRefCopy_b";
constexpr std::uintptr_t TypeDesc_HashName = 0x1404fd5d0ull;
constexpr const char* TypeDesc_HashName_Pattern = "TypeDesc_HashName";
constexpr std::uintptr_t TypeDesc_HashName_b = 0x1401c96e0ull;
constexpr const char* TypeDesc_HashName_b_Pattern = "TypeDesc_HashName_b";
constexpr std::uintptr_t oCString_Dtor = 0x140111d90ull;
constexpr const char* oCString_Dtor_Pattern = "oCString_Dtor";

// --- netcode ---
constexpr std::uintptr_t Entity_GetNetComponent = 0x140312db0ull;
constexpr const char* Entity_GetNetComponent_Pattern = "Entity_GetNetComponent";
constexpr std::uintptr_t Netcode_Channel_LookupById = 0x1402455a0ull;
constexpr const char* Netcode_Channel_LookupById_Pattern = "Netcode_Channel_LookupById";
constexpr std::uintptr_t Netcode_Channel_Unsubscribe = 0x1401c8da0ull;
constexpr const char* Netcode_Channel_Unsubscribe_Pattern = "Netcode_Channel_Unsubscribe";
constexpr std::uintptr_t Netcode_DropPeer = 0x1402cc9c0ull;
constexpr const char* Netcode_DropPeer_Pattern = "Netcode_DropPeer";
constexpr std::uintptr_t Netcode_EntityReplSetup = 0x14073dda0ull;
constexpr const char* Netcode_EntityReplSetup_Pattern = "Netcode_EntityReplSetup";
constexpr std::uintptr_t Netcode_PeerStateTick = 0x1402c7e70ull;
constexpr const char* Netcode_PeerStateTick_Pattern = "Netcode_PeerStateTick";

// --- options ---
constexpr std::uintptr_t g_GameOptions = 0x14143cb58ull;

// --- resource ---
constexpr std::uintptr_t Definitions_LoadGroup = 0x14030fa00ull;
constexpr const char* Definitions_LoadGroup_Pattern = "Definitions_LoadGroup";
constexpr std::uintptr_t InitialLoading_LoadAllDefinitions = 0x140260b80ull;
constexpr const char* InitialLoading_LoadAllDefinitions_Pattern = "InitialLoading_LoadAllDefinitions";
constexpr std::uintptr_t Registry_EnumInstances = 0x1402452a0ull;
constexpr const char* Registry_EnumInstances_Pattern = "Registry_EnumInstances";
constexpr std::uintptr_t Registry_RegisterInstance = 0x1403183efull;
constexpr const char* Registry_RegisterInstance_Pattern = "Registry_RegisterInstance";
constexpr std::uintptr_t ResourceRef_Resolve = 0x1404a51d0ull;
constexpr const char* ResourceRef_Resolve_Pattern = "ResourceRef_Resolve";
constexpr std::uintptr_t Resource_LookupByPath = 0x14049b2a0ull;
constexpr const char* Resource_LookupByPath_Pattern = "Resource_LookupByPath";

// --- rewards ---
constexpr std::uintptr_t CustomFlagList_ContainsAll = 0x140682810ull;
constexpr const char* CustomFlagList_ContainsAll_Pattern = "CustomFlagList_ContainsAll";
constexpr std::uintptr_t CustomFlagList_ContainsAny = 0x140682930ull;
constexpr const char* CustomFlagList_ContainsAny_Pattern = "CustomFlagList_ContainsAny";
constexpr std::uintptr_t RewardDef_Deserialize = 0x1403244c0ull;
constexpr const char* RewardDef_Deserialize_Pattern = "RewardDef_Deserialize";
constexpr std::uintptr_t RewardItem_Serialize = 0x140323dd0ull;
constexpr const char* RewardItem_Serialize_Pattern = "RewardItem_Serialize";
constexpr std::uintptr_t RewardSelectorSettings_Serialize = 0x140340470ull;
constexpr const char* RewardSelectorSettings_Serialize_Pattern = "RewardSelectorSettings_Serialize";
constexpr std::uintptr_t RewardType_Serialize = 0x140324260ull;
constexpr const char* RewardType_Serialize_Pattern = "RewardType_Serialize";
constexpr std::uintptr_t Reward_GenerateAndDistribute = 0x1401ecd10ull;
constexpr const char* Reward_GenerateAndDistribute_Pattern = "Reward_GenerateAndDistribute";
constexpr std::uintptr_t Reward_InitAllRewards = 0x1401e9800ull;
constexpr const char* Reward_InitAllRewards_Pattern = "Reward_InitAllRewards";

// --- skins ---
constexpr std::uintptr_t SkinGrid_Populate = 0x1401f4e80ull;
constexpr const char* SkinGrid_Populate_Pattern = "SkinGrid_Populate";
constexpr std::uintptr_t SkinRoster_Build = 0x1401e0550ull;
constexpr const char* SkinRoster_Build_Pattern = "SkinRoster_Build";
constexpr std::uintptr_t g_RosterManager = 0x141436590ull;

// --- ui ---
constexpr std::uintptr_t BookController_ResolveSettings = 0x140307a30ull;
constexpr const char* BookController_ResolveSettings_Pattern = "BookController_ResolveSettings";
constexpr std::uintptr_t BookController_ResolveTabs = 0x140311060ull;
constexpr const char* BookController_ResolveTabs_Pattern = "BookController_ResolveTabs";
constexpr std::uintptr_t UiButton_InputPoll = 0x1407d5dc0ull;
constexpr const char* UiButton_InputPoll_Pattern = "UiButton_InputPoll";
constexpr std::uintptr_t UiButton_PressCommit = 0x1406a08a0ull;
constexpr const char* UiButton_PressCommit_Pattern = "UiButton_PressCommit";

}  // namespace Sym
