// GENERATED by `rsmm symbols gen` from data/symbols.json — DO NOT EDIT.
// Preferred-base addresses; the loader rebases by image-base delta and,
// for `pattern`-backed symbols, re-resolves via data/function_patterns.json.
#pragma once
#include <cstdint>

namespace Sym {
constexpr std::uintptr_t kPreferredBase = 0x140000000ull;

// --- enemies ---
constexpr std::uintptr_t EnemyCamp_Stage3Filter = 0x1403194c0ull;
constexpr const char* EnemyCamp_Stage3Filter_Pattern = "FUN_1403194c0";
constexpr std::uintptr_t EnemyCamp_TierSelector = 0x14032de90ull;
constexpr const char* EnemyCamp_TierSelector_Pattern = "FUN_14032de90";
constexpr std::uintptr_t EnemyCamp_TribeEntryBuilder = 0x14032f520ull;
constexpr const char* EnemyCamp_TribeEntryBuilder_Pattern = "FUN_14032f520";
constexpr std::uintptr_t EnemyDef_PostLoad = 0x140319f00ull;
constexpr const char* EnemyDef_PostLoad_Pattern = "FUN_140319f00";
constexpr std::uintptr_t EnemyDefinition_ctor = 0x1401dea90ull;
constexpr const char* EnemyDefinition_ctor_Pattern = "FUN_1401dea90";
constexpr std::uintptr_t EnemyTribeDef_PostLoad = 0x14031b1e0ull;
constexpr const char* EnemyTribeDef_PostLoad_Pattern = "FUN_14031b1e0";
constexpr std::uintptr_t EnemyTribeDefinition_ctor = 0x1400c5430ull;
constexpr const char* EnemyTribeDefinition_ctor_Pattern = "FUN_1400c5430";
constexpr std::uintptr_t Enemy_RuntimeSpawnPicker = 0x140330db0ull;
constexpr const char* Enemy_RuntimeSpawnPicker_Pattern = "FUN_140330db0";
constexpr std::uintptr_t MapCtx_DistributeEnemyCampTiers = 0x1401e8050ull;
constexpr const char* MapCtx_DistributeEnemyCampTiers_Pattern = "FUN_1401e8050";

// --- engine ---
constexpr std::uintptr_t Entry_Ctor = 0x140214bb0ull;
constexpr const char* Entry_Ctor_Pattern = "FUN_140214bb0";
constexpr std::uintptr_t Format_String = 0x140204f30ull;
constexpr const char* Format_String_Pattern = "FUN_140204f30";
constexpr std::uintptr_t LevelLoad_Orchestrator = 0x14028dcf0ull;
constexpr const char* LevelLoad_Orchestrator_Pattern = "FUN_14028dcf0";
constexpr std::uintptr_t String_Assign = 0x1405288b0ull;
constexpr const char* String_Assign_Pattern = "FUN_1405288b0";
constexpr std::uintptr_t Vector_Grow = 0x140154c20ull;
constexpr const char* Vector_Grow_Pattern = "FUN_140154c20";

// --- engine-core ---
constexpr std::uintptr_t ClassRegistry_FindByKey = 0x14050b2d0ull;
constexpr const char* ClassRegistry_FindByKey_Pattern = "FUN_14050b2d0";
constexpr std::uintptr_t ClassRegistry_Global = 0x141436690ull;
constexpr std::uintptr_t CustomFlagFilter_Serialize = 0x140669fa0ull;
constexpr const char* CustomFlagFilter_Serialize_Pattern = "FUN_140669fa0";
constexpr std::uintptr_t CustomFlagList_Serialize = 0x140669310ull;
constexpr const char* CustomFlagList_Serialize_Pattern = "FUN_140669310";
constexpr std::uintptr_t GameScene_FindContextByTester = 0x14066bb10ull;
constexpr const char* GameScene_FindContextByTester_Pattern = "FUN_14066bb10";
constexpr std::uintptr_t Profiler_GetThreadScopeStack = 0x140521f20ull;
constexpr const char* Profiler_GetThreadScopeStack_Pattern = "FUN_140521f20";
constexpr std::uintptr_t Property_EvaluateByGuid = 0x1406aa950ull;
constexpr const char* Property_EvaluateByGuid_Pattern = "FUN_1406aa950";
constexpr std::uintptr_t ResourceRef_Serialize = 0x1401c8720ull;
constexpr const char* ResourceRef_Serialize_Pattern = "FUN_1401c8720";
constexpr std::uintptr_t Serializer_GetClassVersion = 0x1404fbea0ull;
constexpr const char* Serializer_GetClassVersion_Pattern = "FUN_1404fbea0";
constexpr std::uintptr_t Serializer_ReadPolyPtrVector = 0x14020d700ull;
constexpr const char* Serializer_ReadPolyPtrVector_Pattern = "FUN_14020d700";
constexpr std::uintptr_t ServiceRegistry_Global = 0x14146f740ull;
constexpr std::uintptr_t StringVector_Serialize = 0x14066c3e0ull;
constexpr const char* StringVector_Serialize_Pattern = "FUN_14066c3e0";

// --- entity ---
constexpr std::uintptr_t EntityValue_Get = 0x1403c71e0ull;
constexpr const char* EntityValue_Get_Pattern = "FUN_1403c71e0";
constexpr std::uintptr_t EntityValue_Lookup = 0x1407481d0ull;
constexpr const char* EntityValue_Lookup_Pattern = "FUN_1407481d0";
constexpr std::uintptr_t Entity_AllocInstance = 0x14068fe90ull;
constexpr const char* Entity_AllocInstance_Pattern = "FUN_14068fe90";
constexpr std::uintptr_t Entity_DispatchHit = 0x1406e2d20ull;
constexpr const char* Entity_DispatchHit_Pattern = "FUN_1406e2d20";
constexpr std::uintptr_t Entity_FindComponentByType = 0x1406ca380ull;
constexpr const char* Entity_FindComponentByType_Pattern = "FUN_1406ca380";
constexpr std::uintptr_t Entity_FindMagicalObjectComponent = 0x1406e2250ull;
constexpr const char* Entity_FindMagicalObjectComponent_Pattern = "FUN_1406e2250";
constexpr std::uintptr_t Entity_GainHealthHandler = 0x1403993f0ull;
constexpr const char* Entity_GainHealthHandler_Pattern = "FUN_1403993f0";
constexpr std::uintptr_t Entity_ModifyHealth = 0x140399a10ull;
constexpr const char* Entity_ModifyHealth_Pattern = "FUN_140399a10";
constexpr std::uintptr_t Entity_ResolveAttackHits = 0x1403dc780ull;
constexpr const char* Entity_ResolveAttackHits_Pattern = "FUN_1403dc780";
constexpr std::uintptr_t HeroController_Ctor = 0x14038e320ull;
constexpr const char* HeroController_Ctor_Pattern = "FUN_14038e320";
constexpr std::uintptr_t HeroController_HudMirror_Ctor = 0x1403b2f20ull;
constexpr const char* HeroController_HudMirror_Ctor_Pattern = "FUN_1403b2f20";
constexpr std::uintptr_t MapCtx_LinkPairedSpawners = 0x1401eb2f0ull;
constexpr const char* MapCtx_LinkPairedSpawners_Pattern = "FUN_1401eb2f0";
constexpr std::uintptr_t g_MagicalObjectComponentMeta = 0x141470768ull;
constexpr std::uintptr_t oCCustomFlagList_vftable = 0x140efc320ull;
constexpr std::uintptr_t oCEntityHitData_vftable = 0x140f0e4b8ull;
constexpr std::uintptr_t oCEntityValueUnion_vftable = 0x140f8fed8ull;

// --- entity-values ---
constexpr std::uintptr_t EntityValueRegistry_RegisterAll = 0x1401d9b70ull;
constexpr const char* EntityValueRegistry_RegisterAll_Pattern = "FUN_1401d9b70";

// --- event ---
constexpr std::uintptr_t Analytics_SubmitNamedEvent = 0x1401fa470ull;
constexpr const char* Analytics_SubmitNamedEvent_Pattern = "FUN_1401fa470";
constexpr std::uintptr_t Crc32_TableInit = 0x14051df80ull;
constexpr const char* Crc32_TableInit_Pattern = "FUN_14051df80";
constexpr std::uintptr_t EventQueue_Drain = 0x140663320ull;
constexpr const char* EventQueue_Drain_Pattern = "FUN_140663320";
constexpr std::uintptr_t Event_LevelUp = 0x1401f6410ull;
constexpr const char* Event_LevelUp_Pattern = "FUN_1401f6410";
constexpr std::uintptr_t Event_RunEnd = 0x1401f51e0ull;
constexpr const char* Event_RunEnd_Pattern = "FUN_1401f51e0";
constexpr std::uintptr_t Id_HashString = 0x14033f7a0ull;
constexpr const char* Id_HashString_Pattern = "FUN_14033f7a0";
constexpr std::uintptr_t NamedEvent_ChannelMap_Find = 0x14066cc50ull;
constexpr const char* NamedEvent_ChannelMap_Find_Pattern = "FUN_14066cc50";
constexpr std::uintptr_t NamedEvent_Delete = 0x140126da0ull;
constexpr const char* NamedEvent_Delete_Pattern = "FUN_140126da0";
constexpr std::uintptr_t NamedEvent_Dispatch = 0x14066a700ull;
constexpr const char* NamedEvent_Dispatch_Pattern = "FUN_14066a700";
constexpr std::uintptr_t NamedEvent_EmitNetworkDamageFromHit = 0x140726610ull;
constexpr const char* NamedEvent_EmitNetworkDamageFromHit_Pattern = "FUN_140726610";
constexpr std::uintptr_t NamedEvent_GiveMagicalObject_Ctor = 0x14030f430ull;
constexpr const char* NamedEvent_GiveMagicalObject_Ctor_Pattern = "FUN_14030f430";
constexpr std::uintptr_t NamedEvent_HeroSubscribeAll = 0x140391d30ull;
constexpr const char* NamedEvent_HeroSubscribeAll_Pattern = "FUN_140391d30";
constexpr std::uintptr_t NamedEvent_HeroUnsubscribeAll = 0x140394a40ull;
constexpr const char* NamedEvent_HeroUnsubscribeAll_Pattern = "FUN_140394a40";
constexpr std::uintptr_t NamedEvent_Id_FromCrc = 0x14051e0e0ull;
constexpr const char* NamedEvent_Id_FromCrc_Pattern = "FUN_14051e0e0";
constexpr std::uintptr_t NamedEvent_NetSend = 0x1407205a0ull;
constexpr const char* NamedEvent_NetSend_Pattern = "FUN_1407205a0";
constexpr std::uintptr_t NamedEvent_NetSendToPeer = 0x140720630ull;
constexpr const char* NamedEvent_NetSendToPeer_Pattern = "FUN_140720630";

// --- heroes ---
constexpr std::uintptr_t HeroDef_LoadBaseEntity = 0x14031e3e0ull;
constexpr const char* HeroDef_LoadBaseEntity_Pattern = "FUN_14031e3e0";
constexpr std::uintptr_t HeroDef_LoadSkinEntity = 0x14031e140ull;
constexpr const char* HeroDef_LoadSkinEntity_Pattern = "FUN_14031e140";

// --- items ---
constexpr std::uintptr_t Entity_GiveHandler = 0x1403a7ba0ull;
constexpr const char* Entity_GiveHandler_Pattern = "FUN_1403a7ba0";
constexpr std::uintptr_t Hero_GrantMagicalObject = 0x140397190ull;
constexpr const char* Hero_GrantMagicalObject_Pattern = "FUN_140397190";
constexpr std::uintptr_t InitialLoading_SpawnMagicalObjects = 0x140260280ull;
constexpr std::uintptr_t MagicalObjectPool_Grow = 0x1401550d0ull;
constexpr const char* MagicalObjectPool_Grow_Pattern = "FUN_1401550d0";
constexpr std::uintptr_t MagicalObjectPool_SourceLookup = 0x1402590c0ull;
constexpr const char* MagicalObjectPool_SourceLookup_Pattern = "FUN_1402590c0";
constexpr std::uintptr_t MagicalObject_RegisterInstance = 0x1403aae40ull;
constexpr const char* MagicalObject_RegisterInstance_Pattern = "FUN_1403aae40";
constexpr std::uintptr_t MagicalObject_SpawnAllObjects = 0x140258760ull;
constexpr const char* MagicalObject_SpawnAllObjects_Pattern = "FUN_1402586f0";
constexpr std::uintptr_t MagicalObject_SpawnContainingFunc = 0x1402586f0ull;
constexpr const char* MagicalObject_SpawnContainingFunc_Pattern = "FUN_1402586f0";
constexpr std::uintptr_t g_MagicalObjectPool = 0x1414365d0ull;

// --- library ---
constexpr std::uintptr_t Definition_DeserializeBase = 0x14030f880ull;
constexpr const char* Definition_DeserializeBase_Pattern = "FUN_14030f880";
constexpr std::uintptr_t GameModifierDef_RegisterAssetLoader = 0x1403257b0ull;
constexpr const char* GameModifierDef_RegisterAssetLoader_Pattern = "FUN_1403257b0";
constexpr std::uintptr_t HasGameModifierStateMachine_Register = 0x140197170ull;
constexpr const char* HasGameModifierStateMachine_Register_Pattern = "FUN_140197170";
constexpr std::uintptr_t Library_AchievementDefinition_vftable = 0x1414113b0ull;
constexpr std::uintptr_t Library_ChallengeDefinition_vftable = 0x141413010ull;
constexpr std::uintptr_t Library_DreamShardDefinition_vftable = 0x141411050ull;
constexpr std::uintptr_t Library_EnemyCampDifficultyDefinition_vftable = 0x141411710ull;
constexpr std::uintptr_t Library_EnemyCampTierDefinition_vftable = 0x141411560ull;
constexpr std::uintptr_t Library_EnemyDefinition_vftable = 0x1414118c0ull;
constexpr std::uintptr_t Library_EnemyTribeDefinition_vftable = 0x141411200ull;
constexpr std::uintptr_t Library_EntitySettingsResource_vftable = 0x141441b60ull;
constexpr std::uintptr_t Library_GameModifierDefinition_vftable = 0x141411b50ull;
constexpr std::uintptr_t Library_IngredientDefinition_vftable = 0x141412c50ull;
constexpr std::uintptr_t Library_MapDefinition_vftable = 0x141412520ull;
constexpr std::uintptr_t Library_MelodyDefinition_vftable = 0x1414129c0ull;
constexpr std::uintptr_t Library_RewardDefinition_vftable = 0x141412e00ull;
constexpr std::uintptr_t Library_TileDefinition_vftable = 0x141412080ull;
constexpr std::uintptr_t Library_VersionDefinition_vftable = 0x141412300ull;
constexpr std::uintptr_t MapDef_RegisterAssetLoader = 0x140322a50ull;
constexpr const char* MapDef_RegisterAssetLoader_Pattern = "FUN_140322a50";
constexpr std::uintptr_t Registry_EnemyDefinition_desc = 0x141470208ull;
constexpr std::uintptr_t Registry_EnemyTribeDefinition_desc = 0x14146f938ull;
constexpr std::uintptr_t RewardDef_RegisterAssetLoader = 0x140323b60ull;
constexpr const char* RewardDef_RegisterAssetLoader_Pattern = "FUN_140323b60";

// --- netcode ---
constexpr std::uintptr_t Entity_GetNetComponent = 0x1403124b0ull;
constexpr const char* Entity_GetNetComponent_Pattern = "FUN_1403124b0";
constexpr std::uintptr_t Netcode_Channel_LookupById = 0x140241150ull;
constexpr const char* Netcode_Channel_LookupById_Pattern = "FUN_140241150";
constexpr std::uintptr_t Netcode_Channel_Unsubscribe = 0x1401c8660ull;
constexpr const char* Netcode_Channel_Unsubscribe_Pattern = "FUN_1401c8660";
constexpr std::uintptr_t Netcode_DropPeer = 0x1402b4450ull;
constexpr std::uintptr_t Netcode_EntityReplSetup = 0x140720c10ull;
constexpr const char* Netcode_EntityReplSetup_Pattern = "FUN_140720c10";
constexpr std::uintptr_t Netcode_PeerStateTick = 0x1402afaa0ull;

// --- options ---
constexpr std::uintptr_t g_GameOptions = 0x141436510ull;

// --- resource ---
constexpr std::uintptr_t Definitions_LoadGroup = 0x14030fa00ull;
constexpr std::uintptr_t InitialLoading_LoadAllDefinitions = 0x14030fa00ull;
constexpr const char* InitialLoading_LoadAllDefinitions_Pattern = "FUN_14030fa00";
constexpr std::uintptr_t Registry_EnumInstances = 0x140240e50ull;
constexpr const char* Registry_EnumInstances_Pattern = "FUN_140240e50";
constexpr std::uintptr_t Registry_RegisterInstance = 0x1403110d0ull;
constexpr const char* Registry_RegisterInstance_Pattern = "FUN_1403110d0";
constexpr std::uintptr_t ResourceRef_Resolve = 0x140491690ull;
constexpr const char* ResourceRef_Resolve_Pattern = "FUN_140491690";
constexpr std::uintptr_t Resource_LookupByPath = 0x140487040ull;
constexpr const char* Resource_LookupByPath_Pattern = "FUN_140487040";

// --- rewards ---
constexpr std::uintptr_t CustomFlagList_ContainsAll = 0x140669cc0ull;
constexpr const char* CustomFlagList_ContainsAll_Pattern = "FUN_140669cc0";
constexpr std::uintptr_t CustomFlagList_ContainsAny = 0x140669de0ull;
constexpr const char* CustomFlagList_ContainsAny_Pattern = "FUN_140669de0";
constexpr std::uintptr_t RewardDef_Deserialize = 0x140323bc0ull;
constexpr const char* RewardDef_Deserialize_Pattern = "FUN_140323bc0";
constexpr std::uintptr_t RewardItem_Serialize = 0x1403234d0ull;
constexpr const char* RewardItem_Serialize_Pattern = "FUN_1403234d0";
constexpr std::uintptr_t RewardSelectorSettings_Serialize = 0x14033fb60ull;
constexpr const char* RewardSelectorSettings_Serialize_Pattern = "FUN_14033fb60";
constexpr std::uintptr_t RewardType_Serialize = 0x140323960ull;
constexpr const char* RewardType_Serialize_Pattern = "FUN_140323960";
constexpr std::uintptr_t Reward_GenerateAndDistribute = 0x1401e9020ull;
constexpr const char* Reward_GenerateAndDistribute_Pattern = "FUN_1401e9020";
constexpr std::uintptr_t Reward_InitAllRewards = 0x1401e6030ull;
constexpr const char* Reward_InitAllRewards_Pattern = "FUN_1401e6030";

// --- skins ---
constexpr std::uintptr_t SkinGrid_Populate = 0x1401f0f10ull;
constexpr const char* SkinGrid_Populate_Pattern = "FUN_1401f0f10";
constexpr std::uintptr_t SkinRoster_Build = 0x1401dcae0ull;
constexpr const char* SkinRoster_Build_Pattern = "FUN_1401dcae0";
constexpr std::uintptr_t g_RosterManager = 0x141436590ull;

}  // namespace Sym
