// GENERATED by `rsmm symbols gen` from data/symbols.json — DO NOT EDIT.
// Typed, pattern-resolved engine call accessors (the Minecraft-style
// 'mappings become callable methods' layer). Each accessor resolves its
// byte pattern via fn_resolve, so it survives game updates.
#pragma once
#include "fn_resolver.h"
#include "symbols.gen.h"
#include <cstdint>

namespace engine {

// Analytics_SubmitNamedEvent  (FUN_1401fa470)
//   void(void* analytics_mgr, void* payload_kv, StringDesc* event_name, char has_run_ctx)
using Analytics_SubmitNamedEvent_fn = void(*)(void*, void*, void*, uint32_t);
inline Analytics_SubmitNamedEvent_fn Analytics_SubmitNamedEvent() {
    return reinterpret_cast<Analytics_SubmitNamedEvent_fn>(rsmm::fn_resolve(Sym::Analytics_SubmitNamedEvent_Pattern));
}

// Entity_AllocInstance  (FUN_14068fe90)
//   void*(void* allocator)
using Entity_AllocInstance_fn = void*(*)(void*);
inline Entity_AllocInstance_fn Entity_AllocInstance() {
    return reinterpret_cast<Entity_AllocInstance_fn>(rsmm::fn_resolve(Sym::Entity_AllocInstance_Pattern));
}

// Entity_FindComponentByType  (FUN_1406ca380)
//   oIEntityCpnt*(oCEntitySpawnerGo* go, oCMetaClass* meta)
using Entity_FindComponentByType_fn = void*(*)(void*, void*);
inline Entity_FindComponentByType_fn Entity_FindComponentByType() {
    return reinterpret_cast<Entity_FindComponentByType_fn>(rsmm::fn_resolve(Sym::Entity_FindComponentByType_Pattern));
}

// Entity_FindMagicalObjectComponent  (FUN_1406e2250)
//   void*(void* instance, void* mo_component_meta)
using Entity_FindMagicalObjectComponent_fn = void*(*)(void*, void*);
inline Entity_FindMagicalObjectComponent_fn Entity_FindMagicalObjectComponent() {
    return reinterpret_cast<Entity_FindMagicalObjectComponent_fn>(rsmm::fn_resolve(Sym::Entity_FindMagicalObjectComponent_Pattern));
}

// Entry_Ctor  (FUN_140214bb0)
//   void(void* base, uint32_t count)
using Entry_Ctor_fn = void(*)(void*, uint32_t);
inline Entry_Ctor_fn Entry_Ctor() {
    return reinterpret_cast<Entry_Ctor_fn>(rsmm::fn_resolve(Sym::Entry_Ctor_Pattern));
}

// Event_LevelUp  (FUN_1401f6410)
using Event_LevelUp_fn = void*(*)(void*, void*);
inline Event_LevelUp_fn Event_LevelUp() {
    return reinterpret_cast<Event_LevelUp_fn>(rsmm::fn_resolve(Sym::Event_LevelUp_Pattern));
}

// Event_RunEnd  (FUN_1401f51e0)
using Event_RunEnd_fn = void*(*)(void*, void*);
inline Event_RunEnd_fn Event_RunEnd() {
    return reinterpret_cast<Event_RunEnd_fn>(rsmm::fn_resolve(Sym::Event_RunEnd_Pattern));
}

// MagicalObjectPool_Grow  (FUN_1401550d0)
//   void(void* pool_plus_0x10, uint32_t count, uint32_t by)
using MagicalObjectPool_Grow_fn = void(*)(void*, uint32_t, uint32_t);
inline MagicalObjectPool_Grow_fn MagicalObjectPool_Grow() {
    return reinterpret_cast<MagicalObjectPool_Grow_fn>(rsmm::fn_resolve(Sym::MagicalObjectPool_Grow_Pattern));
}

// MagicalObjectPool_SourceLookup  (FUN_1402590c0)
//   void*(void* pool, void* out, void* id)
using MagicalObjectPool_SourceLookup_fn = void*(*)(void*, void*, void*);
inline MagicalObjectPool_SourceLookup_fn MagicalObjectPool_SourceLookup() {
    return reinterpret_cast<MagicalObjectPool_SourceLookup_fn>(rsmm::fn_resolve(Sym::MagicalObjectPool_SourceLookup_Pattern));
}

// MagicalObject_SpawnAllObjects  (FUN_1402586f0)
//   void(void* pool, void* scene)
using MagicalObject_SpawnAllObjects_fn = void(*)(void*, void*);
inline MagicalObject_SpawnAllObjects_fn MagicalObject_SpawnAllObjects() {
    std::uintptr_t a = rsmm::fn_resolve(Sym::MagicalObject_SpawnAllObjects_Pattern);
    return a ? reinterpret_cast<MagicalObject_SpawnAllObjects_fn>(a + 0x70) : nullptr;
}

// Resource_LookupByPath  (FUN_140487040)
//   void*(const char* decoded_path, void*, void*, void*)
using Resource_LookupByPath_fn = void*(*)(const char*, void*, void*, void*);
inline Resource_LookupByPath_fn Resource_LookupByPath() {
    return reinterpret_cast<Resource_LookupByPath_fn>(rsmm::fn_resolve(Sym::Resource_LookupByPath_Pattern));
}

// SkinGrid_Populate  (FUN_1401f0f10)
//   void(void* ctx, void* arg)
using SkinGrid_Populate_fn = void(*)(void*, void*);
inline SkinGrid_Populate_fn SkinGrid_Populate() {
    return reinterpret_cast<SkinGrid_Populate_fn>(rsmm::fn_resolve(Sym::SkinGrid_Populate_Pattern));
}

// String_Assign  (FUN_1405288b0)
//   void(void* dst_slot, const StringDesc* src)
using String_Assign_fn = void(*)(void*, const void*);
inline String_Assign_fn String_Assign() {
    return reinterpret_cast<String_Assign_fn>(rsmm::fn_resolve(Sym::String_Assign_Pattern));
}

// Vector_Grow  (FUN_140154c20)
//   void(void* vec, void* /*dead RDX*/, uint32_t new_cap /*R8*/)
using Vector_Grow_fn = void(*)(void*, uint64_t, uint32_t);
inline Vector_Grow_fn Vector_Grow() {
    return reinterpret_cast<Vector_Grow_fn>(rsmm::fn_resolve(Sym::Vector_Grow_Pattern));
}

}  // namespace engine
