#!/usr/bin/env python3
"""Generate the loader's WinHTTP pass-through thunks from exports/winhttp.def.

The proxy used to pass most of the WinHTTP API on with .def FORWARDERS
(`WinHttpOpen=winhttp_real.WinHttpOpen`). A forwarder names its target module
by base name only, so the real WinHTTP had to be a renamed copy of the system
DLL sitting in the game folder. On native Windows that copy fails: a player's
every Stormancer and MyNacon request died instantly with cpprest's
"Open failed" while the loader was planted, and the very same bytes worked
once restore moved them back to `winhttp.dll` (2026-10-09). The genuine module
is `System32\\winhttp.dll`, which a forwarder cannot name -- `winhttp` would
resolve to the proxy itself.

So each pass-through export is a thunk instead: `jmp` through a table that the
loader fills, on first use, from whichever real module it chose
(`real_winhttp()` in hook_backend.cpp). This script writes

  * src/winhttp_thunks.S        one thunk per `X=rsmm_fwd_X` line of the .def
  * src/winhttp_fwd_names.inc   the matching names, in table order

`--check` exits 1 when either file is out of date (CI and tests run it).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

LOADER = Path(__file__).resolve().parent.parent / "src" / "loader"
DEF = LOADER / "exports" / "winhttp.def"
ASM = LOADER / "src" / "winhttp_thunks.S"
INC = LOADER / "src" / "winhttp_fwd_names.inc"

_LINE = re.compile(r"^\s*(\w+)\s*=\s*rsmm_fwd_(\w+)\s*$")

HEADER = ("/* GENERATED by scripts/gen_winhttp_thunks.py from exports/winhttp.def"
          " -- do not edit. */\n")


def forwarded(def_text: str) -> list[str]:
    names = []
    for line in def_text.splitlines():
        m = _LINE.match(line)
        if m:
            if m.group(1) != m.group(2):
                raise SystemExit(f"winhttp.def: {line.strip()!r} must forward X to rsmm_fwd_X")
            names.append(m.group(1))
    if not names:
        raise SystemExit("winhttp.def: no `X=rsmm_fwd_X` exports found")
    return names


def render_asm(names: list[str]) -> str:
    out = [HEADER, """\
/*
 * x64 Windows ABI. The fast path is two instructions and a tail jump, so the
 * real function sees the caller's registers, stack and return address
 * untouched. The slow path (first call of each export) saves the four integer
 * argument registers -- no WinHTTP export takes a float -- asks
 * rsmm_winhttp_resolve() for the address, restores them and jumps.
 * rsmm_winhttp_resolve never returns null: a missing export resolves to a stub
 * that fails with ERROR_PROC_NOT_FOUND.
 */
    .text

    .p2align 4
rsmm_fwd_slow:
    push %rcx
    push %rdx
    push %r8
    push %r9
    sub $40, %rsp            /* 32 shadow + 8 to realign: 8 + 4*8 + 40 = 80 */
    mov %eax, %ecx
    call rsmm_winhttp_resolve
    add $40, %rsp
    pop %r9
    pop %r8
    pop %rdx
    pop %rcx
    jmp *%rax
"""]
    for i, name in enumerate(names):
        out.append(f"""
    .globl rsmm_fwd_{name}
    .p2align 4
rsmm_fwd_{name}:
    mov rsmm_winhttp_fwd+{8 * i}(%rip), %rax
    test %rax, %rax
    jz 1f
    jmp *%rax
1:  mov ${i}, %eax
    jmp rsmm_fwd_slow
""")
    return "".join(out)


def render_inc(names: list[str]) -> str:
    return HEADER + "".join(f'"{n}",\n' for n in names)


def main(argv: list[str]) -> int:
    names = forwarded(DEF.read_text(encoding="utf-8"))
    want = {ASM: render_asm(names), INC: render_inc(names)}
    if "--check" in argv:
        stale = [p.name for p, text in want.items()
                 if not p.is_file() or p.read_text(encoding="utf-8") != text]
        if stale:
            print(f"out of date: {', '.join(stale)} -- run scripts/gen_winhttp_thunks.py",
                  file=sys.stderr)
            return 1
        return 0
    for p, text in want.items():
        p.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {len(names)} thunks")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
