// GENERATED by `rsmm symbols gen` from data/symbols.json — DO NOT EDIT.
// Builds the JSON payload for each gameplay event. Field exprs are
// RE-verified reads off ctx/arg; see the event's payload schema.
//
// Every decode is a PAGE-GUARDED read (mem_load): the offsets are
// RE-derived, so a game patch that moves a field would otherwise turn
// each event fire into a wild read on the game's own thread. When a
// field can't be read the event still publishes, via the safe
// envelope, instead of faulting.
#pragma once
#include <cstdint>
#include <cstdio>
#include <cstring>

#include "mem_safe.h"

namespace rsmm {
inline void event_payload(const char* ev, char* buf, size_t n,
                          unsigned seq, void* ctx, void* arg) {
    (void)ctx; (void)arg;
    if (std::strcmp(ev, "level_up") == 0) {
        bool ok = true;
        int level{};
        ok = ok && mem_load(reinterpret_cast<std::uintptr_t>(ctx) + 0xcc, &level);
        if (ok) {
            std::snprintf(buf, n, "{\"event\":\"level_up\",\"seq\":%u,\"level\":%d}", seq, level);
            return;
        }
        // unreadable field -> fall through to the envelope
    }
    // default: safe envelope (no schema for this event yet)
    std::snprintf(buf, n,
                  "{\"event\":\"%s\",\"seq\":%u,\"ctx\":\"0x%llx\",\"arg\":\"0x%llx\"}",
                  ev, seq,
                  (unsigned long long)(std::uintptr_t)ctx,
                  (unsigned long long)(std::uintptr_t)arg);
}
}  // namespace rsmm
