// GENERATED by `rsmm symbols gen` from data/symbols.json — DO NOT EDIT.
// Spliced into EventHook g_hooks[] in hook_events.cpp.
// { pattern_name, lua_event, real=nullptr, va=0 }
{ "Event_LevelUp", "level_up", nullptr, 0 },
{ "Event_RunEnd", "run_end", nullptr, 0 },
