// GENERATED by `rsmm symbols gen` from data/symbols.json — DO NOT EDIT.
// Payload layouts for oCGameNamedEvent subclasses that carry data.
// Offsets and widths are recovered from the binary; MEANING is not,
// so most field names are mechanical (u50 = u32 at +0x50).
//
// RVAs are build-specific — the decoder is gated on the build
// fingerprint (Loader::va_globals_trusted) so a patched game falls
// back to the plain envelope instead of decoding at moved offsets.
#pragma once
#include <cstdint>

namespace rsmm {

struct EventField { std::uint16_t off; char type; const char* name; };
struct EventSchema {
    std::uint32_t vft_rva;
    const char* cls;
    const EventField* fields;
    std::uint16_t count;
};

// oCGameNamedEventNetworkDamageResponse  (6 construction sites)
inline constexpr EventField kEventFields0[] = {
    { 0x50, 'q', "u50" },
    { 0x60, 'q', "target_entity" },
    { 0x68, 'q', "u68" },
    { 0x6c, 'u', "u6c" },
    { 0x70, 'q', "u70" },
    { 0x74, 'u', "u74" },
    { 0x78, 'q', "u78" },
    { 0x7c, 'u', "u7c" },
    { 0x80, 'q', "u80" },
    { 0x88, 'q', "u88" },
    { 0x90, 'u', "u90" },
    { 0x94, 'q', "u94" },
    { 0x9c, 'q', "u9c" },
    { 0xa4, 'u', "ua4" },
    { 0xa8, 'q', "ua8" },
    { 0xb0, 'q', "ub0" },
    { 0xb8, 'u', "ub8" },
    { 0xbc, 'u', "ubc" },
    { 0xc0, 'q', "uc0" },
    { 0xc8, 'q', "uc8" },
    { 0xd0, 'q', "ud0" },
    { 0xd8, 'w', "ud8" },
    { 0xe0, 'q', "ue0" },
    { 0xf0, 'q', "instigator_entity" },
    { 0x100, 'b', "u100" },
};
// oCNamedEventNetworkWithData  (11 construction sites)
inline constexpr EventField kEventFields1[] = {
    { 0x38, 'q', "u38" },
    { 0x40, 'f', "f40" },
    { 0x50, 'q', "u50" },
    { 0x58, 'q', "u58" },
    { 0x68, 'w', "u68" },
    { 0x6a, 'b', "u6a" },
    { 0x80, 'q', "u80" },
    { 0x88, 'q', "u88" },
    { 0x90, 'q', "u90" },
    { 0x98, 'u', "u98" },
    { 0xa0, 'u', "ua0" },
    { 0xa8, 'u', "ua8" },
    { 0x130, 'q', "u130" },
    { 0x138, 'q', "u138" },
};
// oCGameNamedEventNetworkDamage  (4 construction sites)
inline constexpr EventField kEventFields2[] = {
    { 0x40, 'f', "value" },
    { 0x48, 'q', "source_id" },
    { 0x50, 'q', "u50" },
    { 0x60, 'q', "target_entity" },
    { 0x68, 'q', "u68" },
    { 0x70, 'q', "u70" },
    { 0x78, 'q', "u78" },
    { 0x80, 'q', "u80" },
    { 0x88, 'q', "u88" },
    { 0x90, 'u', "u90" },
    { 0x94, 'q', "u94" },
    { 0x9c, 'q', "u9c" },
    { 0xa4, 'u', "ua4" },
    { 0xa8, 'q', "ua8" },
    { 0xb0, 'q', "ub0" },
    { 0xb8, 'u', "ub8" },
    { 0xbc, 'u', "ubc" },
    { 0xc0, 'q', "uc0" },
    { 0xc8, 'q', "uc8" },
    { 0xd8, 'w', "ud8" },
    { 0xe0, 'q', "ue0" },
    { 0xf0, 'q', "instigator_entity" },
    { 0x100, 'b', "u100" },
};
// NamedEventGameEnd  (6 construction sites)
inline constexpr EventField kEventFields3[] = {
    { 0x50, 'q', "u50" },
    { 0x58, 'u', "u58" },
    { 0x5c, 'u', "u5c" },
    { 0x60, 'u', "u60" },
    { 0x64, 'u', "u64" },
    { 0x68, 'u', "u68" },
    { 0x6c, 'w', "u6c" },
    { 0x6e, 'b', "u6e" },
    { 0x70, 'q', "u70" },
    { 0x78, 'q', "u78" },
    { 0x80, 'u', "u80" },
    { 0xa8, 'u', "ua8" },
    { 0xb0, 'q', "ub0" },
    { 0xb8, 'f', "fb8" },
    { 0xc0, 'q', "uc0" },
    { 0xc8, 'q', "uc8" },
    { 0xd0, 'q', "ud0" },
    { 0xd8, 'u', "ud8" },
    { 0xdc, 'f', "fdc" },
    { 0xe0, 'f', "fe0" },
    { 0xe4, 'w', "ue4" },
    { 0xe6, 'b', "ue6" },
    { 0x108, 'q', "u108" },
    { 0x110, 'q', "u110" },
    { 0x198, 'q', "u198" },
};
// oCDtNamedEventInteraction  (8 construction sites)
inline constexpr EventField kEventFields4[] = {
    { 0x38, 'q', "u38" },
    { 0x50, 'q', "u50" },
};
// oCDtNamedEventGainDreamShards  (6 construction sites)
inline constexpr EventField kEventFields5[] = {
    { 0x50, 'q', "u50" },
    { 0x58, 'u', "u58" },
    { 0x5c, 'b', "u5c" },
    { 0x5d, 'b', "u5d" },
};
// NamedEventRemoveMelody  (3 construction sites)
inline constexpr EventField kEventFields6[] = {
    { 0x50, 'q', "u50" },
    { 0x58, 'u', "u58" },
    { 0x5c, 'u', "u5c" },
};
// oCDtNamedEventGainHealthResource  (8 construction sites)
inline constexpr EventField kEventFields7[] = {
    { 0x58, 'q', "u58" },
    { 0x60, 'u', "u60" },
    { 0x64, 'u', "u64" },
};
// oCDtNamedEventLevelUp  (5 construction sites)
inline constexpr EventField kEventFields8[] = {
    { 0x50, 'u', "u50" },
};
// oCDtNamedEventPowerUpCollectRequest  (5 construction sites)
inline constexpr EventField kEventFields9[] = {
    { 0x50, 'q', "u50" },
};
// oCDtNamedEventExpGain  (5 construction sites)
inline constexpr EventField kEventFields10[] = {
    { 0x50, 'u', "u50" },
};
// oCNamedEventGainHealth  (11 construction sites)
inline constexpr EventField kEventFields11[] = {
    { 0x50, 'u', "u50" },
    { 0x54, 'b', "u54" },
    { 0x55, 'b', "u55" },
    { 0xf8, 'f', "ff8" },
    { 0x108, 'q', "u108" },
};
// NamedEventChooseMelody  (3 construction sites)
inline constexpr EventField kEventFields12[] = {
    { 0x50, 'q', "u50" },
    { 0x58, 'u', "u58" },
    { 0x5c, 'u', "u5c" },
};
// oCDtNamedEventGainReroll  (5 construction sites)
inline constexpr EventField kEventFields13[] = {
    { 0x50, 'w', "u50" },
};
// oCGameEventGainIngredient  (7 construction sites)
inline constexpr EventField kEventFields14[] = {
    { 0x50, 'u', "u50" },
    { 0x54, 'w', "u54" },
};
// oCDtNamedEventExpGainNotif  (5 construction sites)
inline constexpr EventField kEventFields15[] = {
    { 0x50, 'u', "u50" },
};
// NamedEventGiveMagicalObject  (5 construction sites)
inline constexpr EventField kEventFields16[] = {
    { 0x50, 'q', "mo_guid_lo" },
    { 0x58, 'q', "mo_guid_hi" },
};
// oCGameEventHitPointModification  (6 construction sites)
inline constexpr EventField kEventFields17[] = {
    { 0x50, 'u', "u50" },
    { 0x54, 'u', "u54" },
    { 0x58, 'u', "u58" },
};
// oCGameEventMaxHitPointModification  (5 construction sites)
inline constexpr EventField kEventFields18[] = {
    { 0x50, 'u', "u50" },
    { 0x54, 'u', "u54" },
    { 0x58, 'u', "u58" },
};
// oCDtNamedEventDPCollectIngredient  (8 construction sites)
inline constexpr EventField kEventFields19[] = {
    { 0x38, 'q', "u38" },
    { 0x50, 'u', "u50" },
};
// oCGameEventNetworkModifier  (21 construction sites)
inline constexpr EventField kEventFields20[] = {
    { 0x38, 'q', "u38" },
    { 0x50, 'u', "u50" },
    { 0x54, 'u', "u54" },
    { 0x58, 'u', "u58" },
    { 0x60, 'q', "u60" },
    { 0x80, 'u', "u80" },
    { 0x84, 'u', "u84" },
    { 0x88, 'u', "u88" },
    { 0x8c, 'b', "u8c" },
    { 0x90, 'q', "u90" },
    { 0xa8, 'q', "ua8" },
    { 0xb0, 'u', "ub0" },
    { 0xb8, 'q', "ub8" },
    { 0xc0, 'q', "uc0" },
    { 0x120, 'q', "u120" },
};
// oCGameNamedEventAttachmentChange  (5 construction sites)
inline constexpr EventField kEventFields21[] = {
    { 0x50, 'q', "u50" },
    { 0x58, 'q', "u58" },
};
// oCNamedEventNetworkMessage  (13 construction sites)
inline constexpr EventField kEventFields22[] = {
    { 0x40, 'q', "u40" },
    { 0x78, 'q', "u78" },
};
// GameNamedEventNetworkBark  (7 construction sites)
inline constexpr EventField kEventFields23[] = {
    { 0x50, 'w', "u50" },
    { 0x54, 'u', "u54" },
};

// Sorted by vftable RVA for binary search.
inline constexpr EventSchema kEventSchemas[] = {
    { 0xf0dd10u, "oCGameNamedEventNetworkDamageResponse", kEventFields0, 25 },
    { 0xf0f180u, "oCNamedEventNetworkWithData", kEventFields1, 14 },
    { 0xf117d0u, "oCGameNamedEventNetworkDamage", kEventFields2, 23 },
    { 0xf209d0u, "NamedEventGameEnd", kEventFields3, 25 },
    { 0xf21130u, "oCDtNamedEventInteraction", kEventFields4, 2 },
    { 0xf224c0u, "oCDtNamedEventGainDreamShards", kEventFields5, 4 },
    { 0xf22608u, "NamedEventRemoveMelody", kEventFields6, 3 },
    { 0xf227b8u, "oCDtNamedEventGainHealthResource", kEventFields7, 3 },
    { 0xf23b30u, "oCDtNamedEventLevelUp", kEventFields8, 1 },
    { 0xf23ef0u, "oCDtNamedEventPowerUpCollectRequest", kEventFields9, 1 },
    { 0xf25270u, "oCDtNamedEventExpGain", kEventFields10, 1 },
    { 0xf25648u, "oCNamedEventGainHealth", kEventFields11, 5 },
    { 0xf25c48u, "NamedEventChooseMelody", kEventFields12, 3 },
    { 0xf263d0u, "oCDtNamedEventGainReroll", kEventFields13, 1 },
    { 0xf26460u, "oCGameEventGainIngredient", kEventFields14, 2 },
    { 0xf269f8u, "oCDtNamedEventExpGainNotif", kEventFields15, 1 },
    { 0xf270f0u, "NamedEventGiveMagicalObject", kEventFields16, 2 },
    { 0xf27810u, "oCGameEventHitPointModification", kEventFields17, 3 },
    { 0xf28690u, "oCGameEventMaxHitPointModification", kEventFields18, 3 },
    { 0xf28d00u, "oCDtNamedEventDPCollectIngredient", kEventFields19, 2 },
    { 0xf322d0u, "oCGameEventNetworkModifier", kEventFields20, 15 },
    { 0xf7bbc8u, "oCGameNamedEventAttachmentChange", kEventFields21, 2 },
    { 0xf9bec0u, "oCNamedEventNetworkMessage", kEventFields22, 2 },
    { 0xf9d890u, "GameNamedEventNetworkBark", kEventFields23, 2 },
};

inline const EventSchema* event_schema_for(std::uint32_t rva) {
    std::size_t lo = 0, hi = sizeof(kEventSchemas) / sizeof(kEventSchemas[0]);
    while (lo < hi) {
        const std::size_t mid = lo + (hi - lo) / 2;
        if (kEventSchemas[mid].vft_rva == rva) return &kEventSchemas[mid];
        if (kEventSchemas[mid].vft_rva < rva) lo = mid + 1; else hi = mid;
    }
    return nullptr;
}

}  // namespace rsmm
