// GENERATED by `rsmm symbols gen` from data/symbols.json — DO NOT EDIT.
// Spliced into EventHook g_hooks[] in hook_events.cpp.
// { pattern_name, lua_event, real=nullptr, va=0 }
{ "FUN_1401f6410", "level_up", nullptr, 0 },
{ "FUN_1401f51e0", "run_end", nullptr, 0 },
