// GENERATED by `rsmm symbols gen` from data/symbols.json — DO NOT EDIT.
// Builds the JSON payload for each gameplay event. Field exprs are
// RE-verified reads off ctx/arg; see the event's payload schema.
#pragma once
#include <cstdint>
#include <cstdio>
#include <cstring>

namespace rsmm {
inline void event_payload(const char* ev, char* buf, size_t n,
                          unsigned seq, void* ctx, void* arg) {
    (void)ctx; (void)arg;
    if (std::strcmp(ev, "level_up") == 0) {
        int level = *(int*)((char*)ctx + 0xcc);
        std::snprintf(buf, n, "{\"event\":\"level_up\",\"seq\":%u,\"level\":%d}", seq, level);
        return;
    }
    // default: safe envelope (no schema for this event yet)
    std::snprintf(buf, n,
                  "{\"event\":\"%s\",\"seq\":%u,\"ctx\":\"0x%llx\",\"arg\":\"0x%llx\"}",
                  ev, seq,
                  (unsigned long long)(std::uintptr_t)ctx,
                  (unsigned long long)(std::uintptr_t)arg);
}
}  // namespace rsmm
