// GENERATED by `rsmm symbols gen` from data/symbols.json — DO NOT EDIT.
// Preferred-base addresses; the loader rebases by image-base delta and,
// for `pattern`-backed symbols, re-resolves via data/function_patterns.json.
#pragma once
#include <cstdint>

namespace Sym {
constexpr std::uintptr_t kPreferredBase = 0x140000000ull;

// --- engine ---
constexpr std::uintptr_t Entry_Ctor = 0x140214bb0ull;
constexpr const char* Entry_Ctor_Pattern = "FUN_140214bb0";
constexpr std::uintptr_t Format_String = 0x140204f30ull;
constexpr const char* Format_String_Pattern = "FUN_140204f30";
constexpr std::uintptr_t String_Assign = 0x1405288b0ull;
constexpr const char* String_Assign_Pattern = "FUN_1405288b0";
constexpr std::uintptr_t Vector_Grow = 0x140154c20ull;
constexpr const char* Vector_Grow_Pattern = "FUN_140154c20";

// --- entity ---
constexpr std::uintptr_t Entity_AllocInstance = 0x14068fe90ull;
constexpr std::uintptr_t Entity_FindComponentByType = 0x1406ca380ull;
constexpr const char* Entity_FindComponentByType_Pattern = "FUN_1406ca380";
constexpr std::uintptr_t Entity_FindMagicalObjectComponent = 0x1406e2250ull;
constexpr std::uintptr_t g_MagicalObjectComponentMeta = 0x141470768ull;

// --- items ---
constexpr std::uintptr_t InitialLoading_SpawnMagicalObjects = 0x140260280ull;
constexpr std::uintptr_t MagicalObjectPool_Grow = 0x1401550d0ull;
constexpr std::uintptr_t MagicalObjectPool_SourceLookup = 0x1402590c0ull;
constexpr std::uintptr_t MagicalObject_SpawnAllObjects = 0x140258760ull;
constexpr const char* MagicalObject_SpawnAllObjects_Pattern = "FUN_1402586f0";
constexpr std::uintptr_t MagicalObject_SpawnContainingFunc = 0x1402586f0ull;
constexpr const char* MagicalObject_SpawnContainingFunc_Pattern = "FUN_1402586f0";
constexpr std::uintptr_t g_MagicalObjectPool = 0x1414365d0ull;

// --- library ---
constexpr std::uintptr_t Library_AchievementDefinition_vftable = 0x1414113b0ull;
constexpr std::uintptr_t Library_ChallengeDefinition_vftable = 0x141413010ull;
constexpr std::uintptr_t Library_DreamShardDefinition_vftable = 0x141411050ull;
constexpr std::uintptr_t Library_EnemyCampDifficultyDefinition_vftable = 0x141411710ull;
constexpr std::uintptr_t Library_EnemyCampTierDefinition_vftable = 0x141411560ull;
constexpr std::uintptr_t Library_EnemyDefinition_vftable = 0x1414118c0ull;
constexpr std::uintptr_t Library_EnemyTribeDefinition_vftable = 0x141411200ull;
constexpr std::uintptr_t Library_EntitySettingsResource_vftable = 0x141441b60ull;
constexpr std::uintptr_t Library_GameModifierDefinition_vftable = 0x141411b50ull;
constexpr std::uintptr_t Library_IngredientDefinition_vftable = 0x141412c50ull;
constexpr std::uintptr_t Library_MapDefinition_vftable = 0x141412520ull;
constexpr std::uintptr_t Library_MelodyDefinition_vftable = 0x1414129c0ull;
constexpr std::uintptr_t Library_RewardDefinition_vftable = 0x141412e00ull;
constexpr std::uintptr_t Library_TileDefinition_vftable = 0x141412080ull;
constexpr std::uintptr_t Library_VersionDefinition_vftable = 0x141412300ull;

// --- netcode ---
constexpr std::uintptr_t Netcode_Channel_LookupById = 0x140241150ull;
constexpr std::uintptr_t Netcode_Channel_Subscribe = 0x1401c8660ull;
constexpr std::uintptr_t Netcode_DropPeer = 0x1402b4450ull;
constexpr std::uintptr_t Netcode_PeerStateTick = 0x1402afaa0ull;

// --- resource ---
constexpr std::uintptr_t Definitions_LoadGroup = 0x14030fa00ull;
constexpr std::uintptr_t Resource_LookupByPath = 0x140487040ull;
constexpr const char* Resource_LookupByPath_Pattern = "FUN_140487040";

// --- rewards ---
constexpr std::uintptr_t Reward_InitAllRewards = 0x1401e6030ull;
constexpr const char* Reward_InitAllRewards_Pattern = "FUN_1401e6030";

// --- skins ---
constexpr std::uintptr_t SkinGrid_Populate = 0x1401f0f10ull;
constexpr const char* SkinGrid_Populate_Pattern = "FUN_1401f0f10";
constexpr std::uintptr_t SkinRoster_Build = 0x1401dcae0ull;
constexpr const char* SkinRoster_Build_Pattern = "FUN_1401dcae0";
constexpr std::uintptr_t g_RosterManager = 0x141436590ull;

}  // namespace Sym
