"""GENERATED by `rsmm symbols gen` from data/symbols.json — DO NOT EDIT."""
from __future__ import annotations

PREFERRED_BASE = 0x140000000

# name -> preferred-base address
ADDR: dict[str, int] = {
    "Analytics_SubmitNamedEvent": 0x1401fa470,
    "Definitions_LoadGroup": 0x14030fa00,
    "Entity_AllocInstance": 0x14068fe90,
    "Entity_FindComponentByType": 0x1406ca380,
    "Entity_FindMagicalObjectComponent": 0x1406e2250,
    "Entry_Ctor": 0x140214bb0,
    "Event_LevelUp": 0x1401f6410,
    "Event_RunEnd": 0x1401f51e0,
    "Format_String": 0x140204f30,
    "InitialLoading_SpawnMagicalObjects": 0x140260280,
    "Library_AchievementDefinition_vftable": 0x1414113b0,
    "Library_ChallengeDefinition_vftable": 0x141413010,
    "Library_DreamShardDefinition_vftable": 0x141411050,
    "Library_EnemyCampDifficultyDefinition_vftable": 0x141411710,
    "Library_EnemyCampTierDefinition_vftable": 0x141411560,
    "Library_EnemyDefinition_vftable": 0x1414118c0,
    "Library_EnemyTribeDefinition_vftable": 0x141411200,
    "Library_EntitySettingsResource_vftable": 0x141441b60,
    "Library_GameModifierDefinition_vftable": 0x141411b50,
    "Library_IngredientDefinition_vftable": 0x141412c50,
    "Library_MapDefinition_vftable": 0x141412520,
    "Library_MelodyDefinition_vftable": 0x1414129c0,
    "Library_RewardDefinition_vftable": 0x141412e00,
    "Library_TileDefinition_vftable": 0x141412080,
    "Library_VersionDefinition_vftable": 0x141412300,
    "MagicalObjectPool_Grow": 0x1401550d0,
    "MagicalObjectPool_SourceLookup": 0x1402590c0,
    "MagicalObject_SpawnAllObjects": 0x140258760,
    "MagicalObject_SpawnContainingFunc": 0x1402586f0,
    "Netcode_Channel_LookupById": 0x140241150,
    "Netcode_Channel_Subscribe": 0x1401c8660,
    "Netcode_DropPeer": 0x1402b4450,
    "Netcode_PeerStateTick": 0x1402afaa0,
    "Resource_LookupByPath": 0x140487040,
    "Reward_InitAllRewards": 0x1401e6030,
    "SkinGrid_Populate": 0x1401f0f10,
    "SkinRoster_Build": 0x1401dcae0,
    "String_Assign": 0x1405288b0,
    "Vector_Grow": 0x140154c20,
    "g_MagicalObjectComponentMeta": 0x141470768,
    "g_MagicalObjectPool": 0x1414365d0,
    "g_RosterManager": 0x141436590,
}

# name -> function-pattern key (version-resilient), when available
PATTERN: dict[str, str] = {
    "Analytics_SubmitNamedEvent": "FUN_1401fa470",
    "Entity_AllocInstance": "FUN_14068fe90",
    "Entity_FindComponentByType": "FUN_1406ca380",
    "Entity_FindMagicalObjectComponent": "FUN_1406e2250",
    "Entry_Ctor": "FUN_140214bb0",
    "Event_LevelUp": "FUN_1401f6410",
    "Event_RunEnd": "FUN_1401f51e0",
    "Format_String": "FUN_140204f30",
    "MagicalObjectPool_Grow": "FUN_1401550d0",
    "MagicalObjectPool_SourceLookup": "FUN_1402590c0",
    "MagicalObject_SpawnAllObjects": "FUN_1402586f0",
    "MagicalObject_SpawnContainingFunc": "FUN_1402586f0",
    "Resource_LookupByPath": "FUN_140487040",
    "Reward_InitAllRewards": "FUN_1401e6030",
    "SkinGrid_Populate": "FUN_1401f0f10",
    "SkinRoster_Build": "FUN_1401dcae0",
    "String_Assign": "FUN_1405288b0",
    "Vector_Grow": "FUN_140154c20",
}

# event name -> Lua event published to mods (R.on(<lua>, cb))
EVENTS: dict[str, str] = {
    "Event_LevelUp": "level_up",
    "Event_RunEnd": "run_end",
}
