"""In-game mod menu — native book-UI page, phase 1 (read-only mod list).

Repurposes the Tuto tab's first quick-guide page (``Tuto_Page_1``) as an
"RSMM Mods" page using only proven data paths (docs/_re/kinds/ui-menus.md):

* The page entity is cloned FROM THE USER'S OWN INSTALL at build time (no
  game bytes ship with rsmm) and its label text-bank KEYS are swapped to
  ``RSMM_Menu_*`` via :mod:`rsmm.engine.entity_strings` (lstr surgery).
  The inline default texts are left untouched.
* The swapped keys are appended to the ``Tutorials~GAM.xls`` text bank with
  our content (``text_patches.append_bank_keys``), so the labels render the
  mod list. Bank appends are count-aligned across all language siblings.
* Everything lands in a normal mod folder (``RSMMMenu``) that ``rsmm apply``
  installs like any other override mod; ``rsmm restore`` removes it.

Phase 2 (interactive enable/disable) needs the button→named-event dispatch
hook — tracked in docs/_re/kinds/ui-menus.md.
"""

from __future__ import annotations

from pathlib import Path

from . import entity_strings as ES
from . import text_patches as TP

# NOTE: must not start with "_" — apply_mods.discover_mods skips those dirs.
MENU_MOD_ID = "RSMMMenu"

#: The page we repurpose (decoded asset-map path, backslash form).
PAGE_DECODED = ("EntitySettings\\GameUis\\All_Book_Pages\\Tuto\\"
                "Tuto_Page_1.entity.ot.EntitySettingsResource.gen")
#: Text bank carrying the page's label keys.
BANK_DECODED = "Text\\Tutorials~GAM.xls.LocalText.gen"

#: Label slots on Tuto_Page_1: original bank key -> our replacement key.
#: Layout (verified from the cooked entity): left page = intro title + one
#: long paragraph; right page = section title + three description rows.
SLOT_KEYS: dict[str, str] = {
    "Quick_Guide_Intro_Title": "RSMM_Menu_Title",
    "Quick_Guide_Intro_Desc": "RSMM_Menu_Body",
    "Quick_Guide_Objective_Title": "RSMM_Menu_List_Title",
    "Quick_Guide_Objective_Desc_1": "RSMM_Menu_Row_1",
    "Quick_Guide_Objective_Desc_2": "RSMM_Menu_Row_2",
    "Quick_Guide_Objective_Desc_3": "RSMM_Menu_Row_3",
}
_ROW_KEYS = ("RSMM_Menu_Row_1", "RSMM_Menu_Row_2", "RSMM_Menu_Row_3")


class ModMenuError(ValueError):
    pass


def _chunk_rows(lines: list[str]) -> list[str]:
    """Distribute mod lines across the page's 3 row labels (newline-joined)."""
    if not lines:
        return ["(no mods installed)", "", ""]
    n = len(_ROW_KEYS)
    per = -(-len(lines) // n)  # ceil
    return ["\n".join(lines[i * per:(i + 1) * per]) for i in range(n)]


def menu_texts(mods: list[dict]) -> dict[str, str]:
    """Bank key -> display text for the menu page.

    ``mods``: [{"id", "name", "version", "enabled"}] as read from the mod
    manifests (the RSMMMenu mod itself should be excluded by the caller).
    """
    enabled = [m for m in mods if m.get("enabled", True)]
    lines = [
        f"{m.get('name') or m['id']} {m.get('version', '')}".strip()
        + ("" if m.get("enabled", True) else "  [disabled]")
        for m in sorted(mods, key=lambda m: str(m.get("name") or m["id"]).lower())
    ]
    rows = _chunk_rows(lines)
    return {
        "RSMM_Menu_Title": "RSMM Mods",
        "RSMM_Menu_Body": (
            f"{len(mods)} mod(s) installed, {len(enabled)} enabled.\n\n"
            "This page is generated by the Ravenswatch Mod Manager at apply "
            "time. Manage mods with the rsmm CLI or the desktop app; re-run "
            "'rsmm menu build' + 'rsmm apply' to refresh this list."
        ),
        "RSMM_Menu_List_Title": "Installed Mods",
        "RSMM_Menu_Row_1": rows[0],
        "RSMM_Menu_Row_2": rows[1],
        "RSMM_Menu_Row_3": rows[2],
    }


def build_menu_assets(cooking_root: Path, dec2enc: dict[str, str],
                      mods: list[dict]) -> dict[str, bytes]:
    """Build every asset of the menu mod: ``{decoded path token: bytes}``.

    Reads the base page + text bank from the user's install (``cooking_root``)
    so no game-derived bytes ever ship with rsmm.
    """
    page_dec = PAGE_DECODED.replace("\\", "/")
    bank_dec_key = BANK_DECODED.replace("\\", "/")
    for dec in (page_dec, bank_dec_key):
        if dec not in dec2enc:
            raise ModMenuError(f"asset map is missing {dec!r} — game update? "
                               f"re-run 'rsmm rebuild-asset-map'")

    def _pristine(dec: str) -> Path:
        """The un-modded cooked file: prefer apply's `.rsmm.bak` backup so a
        rebuild after `rsmm apply` doesn't re-edit its own output."""
        p = cooking_root / Path(*dec2enc[dec].replace("\\", "/").split("/"))
        bak = p.with_name(p.name + ".rsmm.bak")
        if bak.is_file():
            return bak
        if not p.is_file():
            raise ModMenuError(f"cooked file not found: {p} — wrong game dir?")
        return p

    page_path = _pristine(page_dec)
    # append_bank_keys resolves .rsmm.bak itself (per sibling) — give it the
    # LIVE path so its language-sibling discovery works.
    bank_path = cooking_root / Path(*dec2enc[bank_dec_key].replace("\\", "/").split("/"))
    if not bank_path.is_file():
        raise ModMenuError(f"cooked file not found: {bank_path} — wrong game dir?")

    page = ES.replace_strings(page_path.read_bytes(), dict(SLOT_KEYS))
    out: dict[str, bytes] = {PAGE_DECODED.replace("\\", "/"): page}

    bank_files = TP.append_bank_keys(bank_path, menu_texts(mods))
    bank_dec = BANK_DECODED.replace("\\", "/")
    for token, blob in bank_files.items():
        dec = bank_dec if token == "__base__" else f"{bank_dec}{token}"
        out[dec] = blob
    return out


def manifest_toml(mod_count: int) -> str:
    return f"""[mod]
id          = "{MENU_MOD_ID}"
name        = "RSMM In-Game Menu"
version     = "0.1.0"
author      = "rsmm"
description = "In-game mod list on the Tutorial tab ({mod_count} mods). Regen: rsmm menu build."
enabled     = true
sdk_version = ">=3.0,<4"
"""
