"""In-game mod menu — native book-UI page, phase 1 (read-only mod list).

Repurposes the Tuto tab's first quick-guide page (``Tuto_Page_1``) as an
"RSMM Mods" page using only proven data paths (docs/_re/kinds/ui-menus.md):

* The page entity is cloned FROM THE USER'S OWN INSTALL at build time (no
  game bytes ship with rsmm) and its label text-bank KEYS are swapped to
  ``RSMM_Menu_*`` via :mod:`rsmm.engine.entity_strings` (lstr surgery).
  The inline default texts are left untouched.
* The swapped keys are appended to the ``Tutorials~GAM.xls`` text bank with
  our content (``text_patches.append_bank_keys``), so the labels render the
  mod list. Bank appends are count-aligned across all language siblings.
* Everything lands in a normal mod folder (``RSMMMenu``) that ``rsmm apply``
  installs like any other override mod; ``rsmm restore`` removes it.

Phase 2 (interactive enable/disable) needs the button→named-event dispatch
hook — tracked in docs/_re/kinds/ui-menus.md.
"""

from __future__ import annotations

from pathlib import Path

from . import entity_strings as ES
from . import text_patches as TP

# NOTE: must not start with "_" — apply_mods.discover_mods skips those dirs.
MENU_MOD_ID = "RSMMMenu"

#: The page we repurpose (decoded asset-map path, backslash form).
PAGE_DECODED = ("EntitySettings\\GameUis\\All_Book_Pages\\Tuto\\"
                "Tuto_Page_1.entity.ot.EntitySettingsResource.gen")
#: Text bank carrying the page's label keys.
BANK_DECODED = "Text\\Tutorials~GAM.xls.LocalText.gen"

#: Label slots on Tuto_Page_1: original bank key -> our replacement key.
#: Layout (verified from the cooked entity): left page = intro title + one
#: long paragraph; right page = section title + three description rows.
SLOT_KEYS: dict[str, str] = {
    "Quick_Guide_Intro_Title": "RSMM_Menu_Title",
    "Quick_Guide_Intro_Desc": "RSMM_Menu_Body",
    "Quick_Guide_Objective_Title": "RSMM_Menu_List_Title",
    "Quick_Guide_Objective_Desc_1": "RSMM_Menu_Row_1",
    "Quick_Guide_Objective_Desc_2": "RSMM_Menu_Row_2",
    "Quick_Guide_Objective_Desc_3": "RSMM_Menu_Row_3",
}
_ROW_KEYS = ("RSMM_Menu_Row_1", "RSMM_Menu_Row_2", "RSMM_Menu_Row_3")


class ModMenuError(ValueError):
    pass


def _chunk_rows(lines: list[str]) -> list[str]:
    """Distribute mod lines across the page's 3 row labels (newline-joined)."""
    if not lines:
        return ["(no mods installed)", "", ""]
    n = len(_ROW_KEYS)
    per = -(-len(lines) // n)  # ceil
    return ["\n".join(lines[i * per:(i + 1) * per]) for i in range(n)]


def menu_texts(mods: list[dict]) -> dict[str, str]:
    """Bank key -> display text for the menu page.

    ``mods``: [{"id", "name", "version", "enabled"}] as read from the mod
    manifests (the RSMMMenu mod itself should be excluded by the caller).
    """
    enabled = [m for m in mods if m.get("enabled", True)]
    lines = [
        f"{m.get('name') or m['id']} {m.get('version', '')}".strip()
        + ("" if m.get("enabled", True) else "  [disabled]")
        for m in sorted(mods, key=lambda m: str(m.get("name") or m["id"]).lower())
    ]
    rows = _chunk_rows(lines)
    return {
        "RSMM_Menu_Title": "RSMM Mods",
        "RSMM_Menu_Body": (
            f"{len(mods)} mod(s) installed, {len(enabled)} enabled.\n\n"
            "Generated by the Ravenswatch Mod Manager at apply time.\n"
            "With the UI hook armed: CLICK a page arrow to select the next "
            "mod, DOUBLE-CLICK to queue an enable/disable toggle for the "
            "selected mod (selection + queue shown in mods/_log.txt).\n"
            "Queued changes take effect after 'rsmm intents apply' (or a "
            "running 'rsmm watch') and a game restart."
        ),
        "RSMM_Menu_List_Title": "Installed Mods",
        "RSMM_Menu_Row_1": rows[0],
        "RSMM_Menu_Row_2": rows[1],
        "RSMM_Menu_Row_3": rows[2],
    }


def build_menu_assets(cooking_root: Path, dec2enc: dict[str, str],
                      mods: list[dict]) -> dict[str, bytes]:
    """Build every asset of the menu mod: ``{decoded path token: bytes}``.

    Reads the base page + text bank from the user's install (``cooking_root``)
    so no game-derived bytes ever ship with rsmm.
    """
    page_dec = PAGE_DECODED.replace("\\", "/")
    bank_dec_key = BANK_DECODED.replace("\\", "/")
    for dec in (page_dec, bank_dec_key):
        if dec not in dec2enc:
            raise ModMenuError(f"asset map is missing {dec!r} — game update? "
                               f"re-run 'rsmm rebuild-asset-map'")

    def _pristine(dec: str) -> Path:
        """The un-modded cooked file: prefer apply's `.rsmm.bak` backup so a
        rebuild after `rsmm apply` doesn't re-edit its own output."""
        p = cooking_root / Path(*dec2enc[dec].replace("\\", "/").split("/"))
        bak = p.with_name(p.name + ".rsmm.bak")
        if bak.is_file():
            return bak
        if not p.is_file():
            raise ModMenuError(f"cooked file not found: {p} — wrong game dir?")
        return p

    page_path = _pristine(page_dec)
    # append_bank_keys resolves .rsmm.bak itself (per sibling) — give it the
    # LIVE path so its language-sibling discovery works.
    bank_path = cooking_root / Path(*dec2enc[bank_dec_key].replace("\\", "/").split("/"))
    if not bank_path.is_file():
        raise ModMenuError(f"cooked file not found: {bank_path} — wrong game dir?")

    page = ES.replace_strings(page_path.read_bytes(), dict(SLOT_KEYS))
    out: dict[str, bytes] = {PAGE_DECODED.replace("\\", "/"): page}

    bank_files = TP.append_bank_keys(bank_path, menu_texts(mods))
    bank_dec = BANK_DECODED.replace("\\", "/")
    for token, blob in bank_files.items():
        dec = bank_dec if token == "__base__" else f"{bank_dec}{token}"
        out[dec] = blob
    return out


#: Press bindings, two layers (docs/_re/kinds/ui-menus.md):
#: 1. RSMM page buttons (phase 5, mods_tab.py): button cpnts cloned into the
#:    Tuto frame page; their desc NAME (RSMM_*) is matched against ui:press's
#:    name field and candidate strings.
#: 2. Arrow fallback (phase 2): generic OPTION_BUTTON click/double-click
#:    protocol, for installs where the appended buttons are absent or fail.
_INIT_LUA_TEMPLATE = '''\
-- GENERATED by `rsmm menu build` — do not edit (regenerated on every build).
-- In-game mod menu actions, v1 (provisional bindings):
--   * needs RSMM_ENABLE_UI_HOOK=1 (Loader features panel or env)
--   * NEXT page arrow  -> select next mod (wraps)
--   * PREV page arrow  -> queue enable/disable toggle for the selected mod
-- Queued intents are consumed on the host by `rsmm intents apply` (or a
-- running `rsmm watch`), then take effect on the next game start.
local R = require "rsmm"

local MENU_MOD_ID = "RSMMMenu"
-- RSMM page buttons (desc name -> action); names injected by the builder
-- from rsmm.engine.mods_tab so page + bindings can't drift apart.
local RSMM_NEXT   = "@BTN_NEXT@"
local RSMM_PREV   = "@BTN_PREV@"
local RSMM_TOGGLE = "@BTN_TOGGLE@"
local NEXT_NAMES = { ["Next_Button"] = true, ["Next Button"] = true }
local PREV_NAMES = { ["Prev_Button"] = true, ["Prev Button"] = true }
-- Playtest 2026-07-06: the book page-turn arrows reuse the options-arrow
-- widget and ALL report name="OPTION_BUTTON" (distinct instances), so next
-- vs prev is not distinguishable by name. Fallback protocol: while the book
-- is open, a single OPTION_BUTTON click selects the next mod; a quick second
-- click on the SAME widget (double-click) toggles the selected mod.
local GENERIC_ARROW = "OPTION_BUTTON"
local DOUBLE_CLICK_S = 0.7

local mods = {}
for _, m in ipairs(R.mods.list()) do
    if m.id ~= MENU_MOD_ID then mods[#mods + 1] = m end
end
table.sort(mods, function(a, b)
    return string.lower(a.name or a.id) < string.lower(b.name or b.id)
end)

local sel = 1
local pending = {}   -- id -> desired enabled state (queued this session)
local book_open = false
local saw_book_event = false
local last_click_t = -math.huge
local last_click_w = nil

local function clock()
    local ok, t = pcall(os.clock)
    return ok and t or 0
end

local function selected()
    return mods[sel]
end

local function announce()
    local m = selected()
    if not m then return end
    local state = m.enabled
    if pending[m.id] ~= nil then state = pending[m.id] end
    R.log(string.format("[rsmm-menu] selected %d/%d: %s (%s%s)", sel, #mods,
        m.name or m.id, state and "enabled" or "disabled",
        pending[m.id] ~= nil and ", queued" or ""))
end

local function toggle()
    local m = selected()
    if not m then return end
    local cur = m.enabled
    if pending[m.id] ~= nil then cur = pending[m.id] end
    local want = not cur
    local op = want and "enable" or "disable"
    if R.mods.request(op, m.id) then
        pending[m.id] = want
        R.log(string.format("[rsmm-menu] queued %s %s — run 'rsmm intents apply'"
            .. " and restart to take effect", op, m.id))
    else
        R.log("[rsmm-menu] intent queue FAILED for " .. m.id)
    end
end

R.on("gameplay:BOOK_MENU_OPEN", function()
    book_open = true
    saw_book_event = true
end)
R.on("gameplay:BOOK_MENU_CLOSED", function()
    book_open = false
    saw_book_event = true
end)

R.on("ui:press", function(ev)
    -- Only act while the book is open when we can tell; without the gameplay
    -- bus armed there is no signal, so fall back to always-on.
    if saw_book_event and not book_open then return end
    if #mods == 0 or type(ev) ~= "table" or type(ev.strings) ~= "table" then
        return
    end
    -- Pinned fields first (widget+0x280 name / +0x1e8 label), candidate
    -- string scan as fallback for widget subclasses with shifted slots.
    local hit_next = NEXT_NAMES[ev.name] or false
    local hit_prev = PREV_NAMES[ev.name] or false
    -- RSMM page buttons: the cloned desc name is the identifier. It may
    -- surface as ev.name or only in the candidate strings — check both.
    local rsmm = nil
    local function match_rsmm(s)
        if s == RSMM_NEXT or s == RSMM_PREV or s == RSMM_TOGGLE then
            rsmm = s
        end
    end
    match_rsmm(ev.name)
    match_rsmm(ev.label)
    for _, c in ipairs(ev.strings) do
        if type(c) == "table" and c.s then
            if NEXT_NAMES[c.s] then hit_next = true end
            if PREV_NAMES[c.s] then hit_prev = true end
            match_rsmm(c.s)
        end
    end
    if rsmm == RSMM_NEXT then
        sel = (sel % #mods) + 1
        announce()
        return
    elseif rsmm == RSMM_PREV then
        sel = ((sel - 2) % #mods) + 1
        announce()
        return
    elseif rsmm == RSMM_TOGGLE then
        toggle()
        return
    end
    if hit_next then
        sel = (sel % #mods) + 1
        announce()
    elseif hit_prev then
        toggle()
    elseif ev.name == GENERIC_ARROW then
        local now = clock()
        if last_click_w == ev.widget and (now - last_click_t) < DOUBLE_CLICK_S then
            -- double-click: toggle the currently selected mod
            last_click_w = nil
            toggle()
        else
            -- single click: advance selection
            last_click_w = ev.widget
            last_click_t = now
            sel = (sel % #mods) + 1
            announce()
        end
    end
end)

R.log(string.format("[rsmm-menu] actions armed: %d mod(s); RSMM page buttons"
    .. " + arrow fallback (needs RSMM_ENABLE_UI_HOOK=1)", #mods))
'''


def _init_lua() -> str:
    from . import mods_tab
    return (_INIT_LUA_TEMPLATE
            .replace("@BTN_NEXT@", mods_tab.BUTTON_NEXT)
            .replace("@BTN_PREV@", mods_tab.BUTTON_PREV)
            .replace("@BTN_TOGGLE@", mods_tab.BUTTON_TOGGLE))


# Public name kept stable for cmd_menu + tests.
def init_lua() -> str:
    return _init_lua()


def manifest_toml(mod_count: int) -> str:
    return f"""[mod]
id          = "{MENU_MOD_ID}"
name        = "RSMM In-Game Menu"
version     = "0.1.0"
author      = "rsmm"
description = "In-game mod menu ({mod_count} mods): MODS tab + list page. Regen: rsmm menu build."
enabled     = true
sdk_version = ">=3.0,<4"
# The MODS tab replaces the Tutorial tab's page with a cloned social page —
# a new-asset + book-rewire path that is not yet in-game confirmed.
experimental = true
"""
