"""Fixed-layout numeric schemas for `kind = "stat"` patches in
`[[patch]]` blocks. Extracted from the removed `make_stat_mod` CLI so
`merge.py` (which composes patches from every enabled mod) still
works. Mod authors no longer write these via CLI; the patch table is
hand-written in `manifest.toml` or generated by the SDK.

Schemas only cover small fixed-size class bodies whose float/int
layout is known. Anything beyond this (variable-length bodies, MO
internals, etc.) needs the runtime SDK route, not [[patch]].
"""

from __future__ import annotations

import struct
from dataclasses import dataclass
from pathlib import Path

MARK_BEGIN = bytes.fromhex("1111bbaa")
MARK_END = bytes.fromhex("2222bbaa")


@dataclass(frozen=True)
class Schema:
    cls: str
    decoded_suffix: str
    expected_body_size: int
    fields: tuple   # ((field_name, offset, struct_fmt), ...)


SCHEMAS: tuple[Schema, ...] = (
    Schema(
        cls="oCGlobalEntityValueSettings",
        decoded_suffix=".globalvalue.ot.GlobalEntityValueSettings.gen",
        expected_body_size=23,
        fields=(("value", 0x0c, "<f"),),
    ),
    Schema(
        cls="GameModifierDefinition",
        decoded_suffix=".gamemodifierdef.ot.meModifierDefinition.gen",
        expected_body_size=29,
        fields=(("value", 0x15, "<f"),),
    ),
    Schema(
        cls="oCDtEnemyCampDifficultyDefinition",
        decoded_suffix=".enemycampdifficultydef.ot.DtEnemyCampDifficultyDefinition.gen",
        expected_body_size=18,
        fields=(
            ("min", 0x0a, "<f"),
            ("max", 0x0e, "<f"),
        ),
    ),
)


@dataclass
class Entry:
    schema: Schema
    cooked_path: Path
    decoded_relpath: str
    short_name: str
    values: dict   # field_name -> current value (float)


def index_entries(cooking: Path, asset_map: dict[str, str]) -> list[Entry]:
    by_suffix: dict[str, Schema] = {s.decoded_suffix.lower(): s for s in SCHEMAS}
    entries: list[Entry] = []
    for enc_rel, dec_rel in asset_map.items():
        low = dec_rel.lower()
        match: Schema | None = None
        for suf, sch in by_suffix.items():
            if low.endswith(suf):
                match = sch
                break
        if match is None:
            continue
        p = cooking / Path(*enc_rel.split("\\"))
        if not p.exists():
            continue
        try:
            d = p.read_bytes()
        except OSError:
            continue
        lb = d.rfind(MARK_BEGIN)
        le = d.rfind(MARK_END)
        if lb == -1 or le <= lb:
            continue
        body = d[lb + 4:le]
        if len(body) != match.expected_body_size:
            continue
        values: dict[str, float] = {}
        for field_name, off, fmt in match.fields:
            values[field_name] = struct.unpack_from(fmt, body, off)[0]
        short = Path(dec_rel.split("\\")[-1]).name.split(".")[0]
        entries.append(Entry(
            schema=match,
            cooked_path=p,
            decoded_relpath=dec_rel.replace("\\", "/"),
            short_name=short,
            values=values,
        ))
    return entries


def patch_field(cooked: bytes, schema: Schema, field_name: str,
                value: float) -> bytes:
    lb = cooked.rfind(MARK_BEGIN)
    le = cooked.rfind(MARK_END)
    if lb == -1 or le <= lb:
        raise ValueError("cooked file has no BEGIN/END markers")
    body_start = lb + 4
    body_len = le - body_start
    if body_len != schema.expected_body_size:
        raise ValueError(
            f"unexpected body size {body_len} (want {schema.expected_body_size})"
        )
    for fn, off, fmt in schema.fields:
        if fn == field_name:
            out = bytearray(cooked)
            struct.pack_into(fmt, out, body_start + off, value)
            return bytes(out)
    raise ValueError(f"unknown field {field_name!r} for {schema.cls}")
