"""Fixed-layout numeric schemas for `kind = "stat"` patches in
`[[patch]]` blocks. Extracted from the removed `make_stat_mod` CLI so
`merge.py` (which composes patches from every enabled mod) still
works. Mod authors no longer write these via CLI; the patch table is
hand-written in `manifest.toml` or generated by the SDK.

Schemas only cover small fixed-size class bodies whose float/int
layout is known. Anything beyond this (variable-length bodies, MO
internals, etc.) needs the runtime SDK route, not [[patch]].

One of the three is NOT fixed-layout, and treating it as one was wrong in
both directions -- see :data:`_UNION_TYPES`.
"""

from __future__ import annotations

import struct
from dataclasses import dataclass
from pathlib import Path

MARK_BEGIN = bytes.fromhex("1111bbaa")
MARK_END = bytes.fromhex("2222bbaa")


@dataclass(frozen=True)
class Schema:
    cls: str
    decoded_suffix: str
    expected_body_size: int
    fields: tuple   # ((field_name, offset, struct_fmt), ...)
    #: Offset of a union TYPE TAG within the body, for classes whose payload
    #: format is not fixed. `None` means the layout above is the whole story.
    union_at: int | None = None


#: `oCGlobalEntityValueSettings` is a TAGGED UNION. The body is::
#:
#:     body+0x00  u32 union_ver = 3
#:     body+0x04  u32 type       0 float, 1 int, 2 bool, 3 vector
#:     body+0x08  u32 pad
#:     body+0x0c  payload        <f | <i | <? (one byte) | 3 x <f
#:
#: and its LENGTH follows the payload, so the single `expected_body_size=23`
#: this table used to carry was right for exactly two of the four types. Of the
#: 204 shipped globals (83 int, 61 float, 57 bool, 3 vector) that meant the 57
#: bools were dropped by `index_entries` as the wrong size -- which is why
#: `Start_Revealed_Map` could not be patched at all -- and, worse, the 83 ints
#: passed the size check and had a FLOAT written into them.
_UNION_TYPES: dict[int, tuple[str, int]] = {
    0: ("<f", 23),
    1: ("<i", 23),
    2: ("<?", 20),
    # 3 = vector: three floats and no single `value` to aim at. Unsupported on
    # purpose -- a scalar patch has no meaning here, so fail closed.
}


SCHEMAS: tuple[Schema, ...] = (
    Schema(
        cls="oCGlobalEntityValueSettings",
        decoded_suffix=".globalvalue.ot.GlobalEntityValueSettings.gen",
        expected_body_size=23,          # the float/int case; see union_at
        fields=(("value", 0x0c, "<f"),),
        union_at=0x04,
    ),
    Schema(
        cls="GameModifierDefinition",
        decoded_suffix=".gamemodifierdef.ot.meModifierDefinition.gen",
        expected_body_size=29,
        fields=(("value", 0x15, "<f"),),
    ),
    Schema(
        cls="oCDtEnemyCampDifficultyDefinition",
        decoded_suffix=".enemycampdifficultydef.ot.DtEnemyCampDifficultyDefinition.gen",
        expected_body_size=18,
        fields=(
            ("min", 0x0a, "<f"),
            ("max", 0x0e, "<f"),
        ),
    ),
)


@dataclass
class Entry:
    schema: Schema
    cooked_path: Path
    decoded_relpath: str
    short_name: str
    values: dict   # field_name -> current value


def _resolved(schema: Schema, body: bytes) -> tuple[tuple, int] | None:
    """`(fields, body_size)` for this body, or None when it is not patchable.

    Resolution is per FILE, not per schema, because the payload format of a
    tagged union is only knowable from the bytes in front of you. Both the
    reader and the writer go through here so they cannot disagree.
    """
    if schema.union_at is None:
        return schema.fields, schema.expected_body_size
    if len(body) < schema.union_at + 4:
        return None
    tag = struct.unpack_from("<I", body, schema.union_at)[0]
    got = _UNION_TYPES.get(tag)
    if got is None:
        return None
    fmt, size = got
    return tuple((fn, off, fmt) for fn, off, _ in schema.fields), size


def index_entries(cooking: Path, asset_map: dict[str, str]) -> list[Entry]:
    by_suffix: dict[str, Schema] = {s.decoded_suffix.lower(): s for s in SCHEMAS}
    entries: list[Entry] = []
    for enc_rel, dec_rel in asset_map.items():
        low = dec_rel.lower()
        match: Schema | None = None
        for suf, sch in by_suffix.items():
            if low.endswith(suf):
                match = sch
                break
        if match is None:
            continue
        p = cooking / Path(*enc_rel.split("\\"))
        if not p.exists():
            continue
        try:
            d = p.read_bytes()
        except OSError:
            continue
        lb = d.rfind(MARK_BEGIN)
        le = d.rfind(MARK_END)
        if lb == -1 or le <= lb:
            continue
        body = d[lb + 4:le]
        resolved = _resolved(match, body)
        if resolved is None:
            continue
        fields, body_size = resolved
        if len(body) != body_size:
            continue
        values: dict = {}
        for field_name, off, fmt in fields:
            values[field_name] = struct.unpack_from(fmt, body, off)[0]
        short = Path(dec_rel.split("\\")[-1]).name.split(".")[0]
        entries.append(Entry(
            schema=match,
            cooked_path=p,
            decoded_relpath=dec_rel.replace("\\", "/"),
            short_name=short,
            values=values,
        ))
    return entries


def patch_field(cooked: bytes, schema: Schema, field_name: str,
                value: float | int | bool) -> bytes:
    lb = cooked.rfind(MARK_BEGIN)
    le = cooked.rfind(MARK_END)
    if lb == -1 or le <= lb:
        raise ValueError("cooked file has no BEGIN/END markers")
    body_start = lb + 4
    resolved = _resolved(schema, cooked[body_start:le])
    if resolved is None:
        raise ValueError(
            f"{schema.cls}: value type is not one this patcher writes "
            f"(vector, or a tag it has never seen) — refusing to guess")
    fields, body_size = resolved
    body_len = le - body_start
    if body_len != body_size:
        raise ValueError(
            f"unexpected body size {body_len} (want {body_size})"
        )
    for fn, off, fmt in fields:
        if fn == field_name:
            out = bytearray(cooked)
            try:
                struct.pack_into(fmt, out, body_start + off, value)
            except struct.error as e:
                # Loud, but as a ValueError: `merge` reports these per field
                # and carries on with the rest of the patch set.
                raise ValueError(
                    f"{value!r} does not fit {schema.cls}.{fn} ({fmt}): {e}"
                ) from None
            return bytes(out)
    raise ValueError(f"unknown field {field_name!r} for {schema.cls}")
