"""Auto-generate the SDK/CLI reference from `@sdk_export` registrations.

Walks `rsmm.sdk.api.registry()`, pulls each function's signature +
docstring, and emits one Markdown file per submodule. Run via
`rsmm docs-gen`.

Two destinations, one source of truth:
- `out_dir` (default `docs/api/`) — plain Markdown, CI `--check`s it.
- `site_out` (default `apps/docs/src/content/docs/reference/sdk-api/`) —
  the same pages with Starlight frontmatter so they render on the docs site.
"""

from __future__ import annotations

import importlib
import inspect
import pkgutil
from pathlib import Path

from .api import registry


def _import_sdk_modules() -> None:
    """Side-effect import every `rsmm.sdk.*` so decorators fire."""
    import logging

    import rsmm.sdk as pkg
    for _, name, _ in pkgutil.walk_packages(pkg.__path__, prefix="rsmm.sdk."):
        try:
            importlib.import_module(name)
        except Exception as e:  # noqa: BLE001 — one bad module shouldn't abort the build
            logging.getLogger(__name__).warning(
                "docs-gen: skipped %s (import failed: %s)", name, e
            )


def _yaml_title(s: str) -> str:
    """Quote a frontmatter title if it contains YAML-significant chars."""
    if any(c in s for c in ':#"\''):
        return '"' + s.replace('"', '\\"') + '"'
    return s


def _write(out_dir: Path | None, site_out: Path | None,
           rel: str, text: str, title: str) -> list[Path]:
    """Write one page to whichever destinations are set. Returns paths written."""
    written: list[Path] = []
    if out_dir is not None:
        p = out_dir / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")
        written.append(p)
    if site_out is not None:
        p = site_out / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(f"---\ntitle: {_yaml_title(title)}\n---\n\n" + text, encoding="utf-8")
        written.append(p)
    return written


def _cli_page() -> tuple[str, str, str]:
    """Return (relpath, body, title) for the CLI inventory page."""
    from rsmm.cli._dispatch import iter_commands

    rows: list[tuple[str, str, str]] = []
    for cmd, modname in sorted(set(iter_commands())):
        try:
            mod = importlib.import_module(modname)
            doc = (inspect.getdoc(mod) or "").strip().splitlines()
            summary = doc[0] if doc else ""
        except Exception as e:  # noqa: BLE001 — report, don't crash docs build
            summary = f"(import failed: {e})"
        rows.append((cmd, modname, summary))

    lines = [
        "# rsmm CLI reference",
        "",
        "Auto-generated by `rsmm docs-gen` from the dispatch table "
        "(`rsmm.cli._dispatch.iter_commands`). Do not edit by hand — run "
        "`rsmm docs-gen` after adding or renaming a subcommand.",
        "",
        "| Command | Module | Summary |",
        "|---|---|---|",
    ]
    for cmd, modname, summary in rows:
        lines.append(f"| `rsmm {cmd}` | `{modname}` | {summary} |")
    return "cli.md", "\n".join(lines) + "\n", "CLI command inventory"


def generate(out_dir: Path | None, site_out: Path | None = None) -> list[Path]:
    """Write one `<module>.md` per SDK submodule + `cli.md` + `README.md`.

    Writes to `out_dir` (plain) and/or `site_out` (with Starlight
    frontmatter). Returns every path written.
    """
    _import_sdk_modules()
    by_module: dict[str, list[tuple[str, callable]]] = {}
    for name, fn in registry().items():
        mod = getattr(fn, "__module__", "rsmm.sdk")
        by_module.setdefault(mod, []).append((name, fn))

    written: list[Path] = []
    module_slugs: list[str] = []
    for mod_name, items in sorted(by_module.items()):
        slug = mod_name.replace("rsmm.sdk.", "").replace(".", "_") or "root"
        module_slugs.append(slug)
        lines = [f"# {mod_name}", ""]
        for name, fn in sorted(items):
            try:
                sig = str(inspect.signature(fn))
            except (TypeError, ValueError):
                sig = "(...)"
            doc = inspect.getdoc(fn) or "(undocumented)"
            lines += [f"## `{name}{sig}`", "", doc, ""]
        written += _write(out_dir, site_out, f"{slug}.md", "\n".join(lines), mod_name)

    # cli.md
    cli_rel, cli_body, cli_title = _cli_page()
    written += _write(out_dir, site_out, cli_rel, cli_body, cli_title)

    # README.md index
    idx_lines = ["# SDK v3 API reference", "",
                 "API version: see `rsmm.sdk.api.API_VERSION`", "",
                 "## CLI", "",
                 "- [cli](cli.md) — every `rsmm` subcommand", "",
                 "## SDK modules", ""]
    for slug in module_slugs:
        idx_lines.append(f"- [{slug}]({slug}.md)")
    # README is a repo-side index only; the docs site uses its sidebar instead,
    # so the relative `.md` links here never reach the link validator.
    written += _write(out_dir, None, "README.md", "\n".join(idx_lines) + "\n",
                      "SDK API reference")
    return written
