"""Auto-generate docs/api/ from `@sdk_export` registrations.

Walks `rsmm.sdk.api.registry()`, pulls each function's signature +
docstring, and emits one Markdown file per submodule. Run via
`rsmm docs-gen`.
"""

from __future__ import annotations

import importlib
import inspect
import pkgutil
from pathlib import Path

from .api import registry


def _import_sdk_modules() -> None:
    """Side-effect import every `rsmm.sdk.*` so decorators fire."""
    import logging

    import rsmm.sdk as pkg
    for _, name, _ in pkgutil.walk_packages(pkg.__path__, prefix="rsmm.sdk."):
        try:
            importlib.import_module(name)
        except Exception as e:  # noqa: BLE001 — one bad module shouldn't abort the build
            logging.getLogger(__name__).warning(
                "docs-gen: skipped %s (import failed: %s)", name, e
            )


def generate_cli(out_dir: Path) -> Path:
    """Write `cli.md` — the authoritative `rsmm <cmd>` inventory.

    Sourced from `rsmm.cli._dispatch.iter_commands()` (the same table
    `main()` routes on), so a new subcommand that isn't regenerated here
    is caught by `rsmm docs-gen --check` in CI.
    """
    from rsmm.cli._dispatch import iter_commands

    rows: list[tuple[str, str, str]] = []
    for cmd, modname in sorted(set(iter_commands())):
        try:
            mod = importlib.import_module(modname)
            doc = (inspect.getdoc(mod) or "").strip().splitlines()
            summary = doc[0] if doc else ""
        except Exception as e:  # noqa: BLE001 — report, don't crash docs build
            summary = f"(import failed: {e})"
        rows.append((cmd, modname, summary))

    lines = [
        "# rsmm CLI reference",
        "",
        "Auto-generated by `rsmm docs-gen` from the dispatch table "
        "(`rsmm.cli._dispatch.iter_commands`). Do not edit by hand — run "
        "`rsmm docs-gen` after adding or renaming a subcommand.",
        "",
        "| Command | Module | Summary |",
        "|---|---|---|",
    ]
    for cmd, modname, summary in rows:
        lines.append(f"| `rsmm {cmd}` | `{modname}` | {summary} |")
    out_dir.mkdir(parents=True, exist_ok=True)
    p = out_dir / "cli.md"
    p.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return p


def generate(out_dir: Path) -> list[Path]:
    """Write one `<module>.md` per SDK submodule + `cli.md`. Returns paths."""
    _import_sdk_modules()
    out_dir.mkdir(parents=True, exist_ok=True)
    by_module: dict[str, list[tuple[str, callable]]] = {}
    for name, fn in registry().items():
        mod = getattr(fn, "__module__", "rsmm.sdk")
        by_module.setdefault(mod, []).append((name, fn))
    written: list[Path] = []
    for mod_name, items in sorted(by_module.items()):
        slug = mod_name.replace("rsmm.sdk.", "").replace(".", "_") or "root"
        lines = [f"# {mod_name}", ""]
        for name, fn in sorted(items):
            try:
                sig = str(inspect.signature(fn))
            except (TypeError, ValueError):
                sig = "(...)"
            doc = inspect.getdoc(fn) or "(undocumented)"
            lines += [f"## `{name}{sig}`", "", doc, ""]
        p = out_dir / f"{slug}.md"
        p.write_text("\n".join(lines), encoding="utf-8")
        written.append(p)
    cli = generate_cli(out_dir)
    index = out_dir / "README.md"
    idx_lines = ["# SDK v3 API reference", "",
                 "API version: see `rsmm.sdk.api.API_VERSION`", "",
                 "## CLI", "",
                 f"- [{cli.stem}]({cli.name}) — every `rsmm` subcommand", "",
                 "## SDK modules", ""]
    for p in sorted(written):
        idx_lines.append(f"- [{p.stem}]({p.name})")
    index.write_text("\n".join(idx_lines) + "\n", encoding="utf-8")
    written += [cli, index]
    return written
